-- Leverantörsregister: utöka med Spiris-fälten (grund- + bokföringsuppgifter)
alter table suppliers
  add column if not exists leverantorsnr text,
  add column if not exists aktiv boolean default true,
  add column if not exists telefon2 text,
  add column if not exists fax text,
  add column if not exists webb text,
  add column if not exists faktura_adress text,
  add column if not exists faktura_adress2 text,
  add column if not exists postnr text,
  add column if not exists ort text,
  add column if not exists land text,
  add column if not exists landskod text,
  add column if not exists plusgiro text,
  add column if not exists bic text,
  add column if not exists iban text,
  add column if not exists kontotyp text,
  add column if not exists bank text,
  add column if not exists clearingnr text,
  add column if not exists kontonr text,
  add column if not exists avgiftskod text,
  add column if not exists betalkod text,
  add column if not exists inaktivera_betalfil boolean default false,
  add column if not exists default_motkonto text,
  add column if not exists konteringsmall text,
  add column if not exists artikelregistrering boolean default false,
  add column if not exists oresavrundning boolean default true,
  add column if not exists momstyp text,
  add column if not exists vat_nummer text,
  add column if not exists valuta text default 'SEK',
  add column if not exists betalningsvillkor text,
  add column if not exists kundnummer text,
  add column if not exists cfar text,
  add column if not exists sni text,
  add column if not exists referens text,
  add column if not exists anteckning text;
