-- Importera BAS 2026 kontoplan (1367 konton)
-- Kör EFTER schema.sql och efter att du skapat ett företag
-- Ersätt COMPANY_ID med ditt företags UUID

-- Exempel: INSERT med placeholder
DO $$
DECLARE
  cid uuid;
BEGIN
  SELECT id INTO cid FROM companies LIMIT 1;
  INSERT INTO accounts (company_id, account_nr, name, vat_code, is_active) VALUES
    (cid, '1010', 'Utvecklingsutgifter', '', false),
    (cid, '1011', 'Balanserade utgifter för utveckling', '', false),
    (cid, '1012', 'Balanserade utgifter för programvaror', '', false),
    (cid, '1018', 'Ackumulerade nedskrivningar på balanserade utgifter', '', false),
    (cid, '1019', 'Ackumulerade avskrivningar på balanserade utgifter', '', false),
    (cid, '1020', 'Koncessioner m.m.', '', false),
    (cid, '1028', 'Ackumulerade nedskrivningar på koncessioner m.m.', '', false),
    (cid, '1029', 'Ackumulerade avskrivningar på koncessioner m.m.', '', false),
    (cid, '1030', 'Patent', '', false),
    (cid, '1038', 'Ackumulerade nedskrivningar på patent', '', false),
    (cid, '1039', 'Ackumulerade avskrivningar på patent', '', false),
    (cid, '1040', 'Licenser', '', false),
    (cid, '1048', 'Ackumulerade nedskrivningar på licenser', '', false),
    (cid, '1049', 'Ackumulerade avskrivningar på licenser', '', false),
    (cid, '1050', 'Varumärken', '', false),
    (cid, '1058', 'Ackumulerade nedskrivningar på varumärken', '', false),
    (cid, '1059', 'Ackumulerade avskrivningar på varumärken', '', false),
    (cid, '1060', 'Hyresrätter och liknande', '', false),
    (cid, '1068', 'Ackumulerade nedskrivningar på hyresrätter och liknande', '', false),
    (cid, '1069', 'Ackumulerade avskrivningar på hyresrätter och liknande', '', false),
    (cid, '1070', 'Goodwill', '', false),
    (cid, '1078', 'Ackumulerade nedskrivningar på goodwill', '', false),
    (cid, '1079', 'Ackumulerade avskrivningar på goodwill', '', false),
    (cid, '1080', 'Pågående projekt och förskott för immateriella anläggningstillgångar', '', false),
    (cid, '1081', 'Pågående projekt för immateriella anläggningstillgångar', '', false),
    (cid, '1088', 'Förskott för immateriella anläggningstillgångar', '', false),
    (cid, '1090', 'Övriga immateriella anläggningstillgångar', '', false),
    (cid, '1092', 'Tomträtter', '', false),
    (cid, '1098', 'Ackumulerade nedskrivningar på övriga immateriella anläggningstillgångar', '', false),
    (cid, '1099', 'Ackumulerade avskrivningar på övriga immateriella anläggningstillgångar', '', false),
    (cid, '1110', 'Byggnader', '', false),
    (cid, '1111', 'Byggnader på egen mark', '', false),
    (cid, '1112', 'Byggnader på annans mark', '', false),
    (cid, '1118', 'Ackumulerade nedskrivningar på byggnader', '', false),
    (cid, '1119', 'Ackumulerade avskrivningar på byggnader', '', false),
    (cid, '1120', 'Förbättringsutgifter på annans fastighet', '', false),
    (cid, '1129', 'Ackumulerade avskrivningar på förbättringsutgifter på annans fastighet', '', false),
    (cid, '1130', 'Mark', '', false),
    (cid, '1140', 'Tomter och obebyggda markområden', '', false),
    (cid, '1150', 'Markanläggningar', '', false),
    (cid, '1158', 'Ackumulerade nedskrivningar på markanläggningar', '', false),
    (cid, '1159', 'Ackumulerade avskrivningar på markanläggningar', '', false),
    (cid, '1180', 'Pågående nyanläggningar och förskott för byggnader och mark', '', false),
    (cid, '1181', 'Pågående ny-, till- och ombyggnad', '', false),
    (cid, '1188', 'Förskott för byggnader och mark', '', false),
    (cid, '1210', 'Maskiner och andra tekniska anläggningar', '', true),
    (cid, '1211', 'Maskiner och andra tekniska anläggningar i övrigt', '', false),
    (cid, '1212', 'Byggnads- och markinventarier (för produktion)', '', false),
    (cid, '1214', 'Datorer (för produktion)', '', false),
    (cid, '1216', 'Arbetsfordon', '', false),
    (cid, '1217', 'Finansiellt leasade maskiner', '', false),
    (cid, '1218', 'Ackumulerade nedskrivningar på maskiner och andra tekniska anläggningar', '', false),
    (cid, '1219', 'Ackumulerade avskrivningar på maskiner och andra tekniska anläggningar', '', false),
    (cid, '1220', 'Inventarier, verktyg och installationer', '', true),
    (cid, '1221', 'Inventarier, verktyg och installationer i övrigt', '', false),
    (cid, '1222', 'Byggnads- och markinventarier (ej för produktion)', '', false),
    (cid, '1224', 'Datorer (ej för produktion)', '', false),
    (cid, '1226', 'Bilar och transportmedel (ej för produktion)', '', false),
    (cid, '1227', 'Finansiellt leasade inventarier', '', false),
    (cid, '1228', 'Ackumulerade nedskrivningar på inventarier, verktyg och installationer', '', false),
    (cid, '1229', 'Ackumulerade avskrivningar på inventarier, verktyg och installationer', '', true),
    (cid, '1230', '(Fritt konto för Maskiner och andra tekniska anläggningar)', '', false),
    (cid, '1240', '(Fritt konto för Maskiner och andra tekniska anläggningar)', '', false),
    (cid, '1248', 'Ackumulerade nedskrivningar på bilar och andra transportmedel', '', false),
    (cid, '1249', 'Ackumulerade avskrivningar på bilar och andra transportmedel', '', false),
    (cid, '1250', '(Fritt konto för Inventarier, verktyg och installationer)', '', false),
    (cid, '1258', 'Ackumulerade nedskrivningar på datorer', '', false),
    (cid, '1259', 'Ackumulerade avskrivningar på datorer', '', false),
    (cid, '1260', '(Fritt konto för Inventarier, verktyg och installationer)', '', false),
    (cid, '1280', 'Pågående nyanläggningar och förskott för maskiner respektive inventarier', '', false),
    (cid, '1281', 'Pågående nyanläggningar, maskiner respektive inventarier', '', false),
    (cid, '1288', 'Förskott för maskiner respektive inventarier', '', false),
    (cid, '1290', 'Övriga materiella anläggningstillgångar', '', false),
    (cid, '1291', 'Konst och liknande tillgångar', '', false),
    (cid, '1292', 'Djur som klassificeras som anläggningstillgång', '', false),
    (cid, '1298', 'Ackumulerade nedskrivningar på övriga materiella anläggningstillgångar', '', false),
    (cid, '1299', 'Ackumulerade avskrivningar på övriga materiella anläggningstillgångar', '', false),
    (cid, '1310', 'Andelar i koncernföretag', '', false),
    (cid, '1311', 'Aktier i noterade svenska koncernföretag', '', false),
    (cid, '1312', 'Aktier i onoterade svenska koncernföretag', '', false),
    (cid, '1313', 'Aktier i noterade utländska koncernföretag', '', false),
    (cid, '1314', 'Aktier i onoterade utländska koncernföretag', '', false),
    (cid, '1316', 'Andra andelar i svenska koncernföretag', '', false),
    (cid, '1317', 'Andra andelar i utländska koncernföretag', '', false),
    (cid, '1318', 'Ackumulerade nedskrivningar av andelar i koncernföretag', '', false),
    (cid, '1320', 'Långfristiga fordringar hos koncernföretag', '', false),
    (cid, '1321', 'Långfristiga fordringar hos moderföretag', '', false),
    (cid, '1322', 'Långfristiga fordringar hos dotterföretag', '', false),
    (cid, '1323', 'Långfristiga fordringar hos andra koncernföretag', '', false),
    (cid, '1328', 'Ackumulerade nedskrivningar av långfristiga fordringar hos koncernföretag', '', false),
    (cid, '1330', 'Andelar i intresseftg, gemensamt styrda ftg, övriga ägarintr ftg', '', false),
    (cid, '1331', 'Andelar i intresseföretag', '', false),
    (cid, '1332', 'Ackumulerade nedskrivningar av andelar i intresseföretag', '', false),
    (cid, '1333', 'Andelar i gemensamt styrda företag', '', false),
    (cid, '1334', 'Ackumulerade nedskrivningar av andelar i gemensamt styrda företag', '', false),
    (cid, '1336', 'Andelar i övriga företag som det finns ett ägarintresse i', '', false),
    (cid, '1337', 'Ackumulerade nedskrivningar av andelar i övriga företag som det finns ett ägarintresse i', '', true),
    (cid, '1340', 'Långfristiga fordringar hos iintresseftg, gemensamt styrda ftg, övriga ägarintr ftg', '', false),
    (cid, '1341', 'Långfristiga fordringar hos intresseföretag', '', false),
    (cid, '1342', 'Ackumulerade nedskrivningar av långfristiga fordringar hos intresseföretag', '', false),
    (cid, '1343', 'Långfristiga fordringar hos gemensamt styrda företag', '', false),
    (cid, '1344', 'Ackumulerade nedskrivningar av långfristiga fordringar hos gemensamt styrda företag', '', false),
    (cid, '1346', 'Långfristiga fordringar hos övriga företag som det finns ett ägarintresse i', '', false),
    (cid, '1347', 'Ackumulerade nedskrivningar av långfristiga fordringar hos övr företag som det finns ett ägarintr i', '', false),
    (cid, '1350', 'Andra långfristiga värdepappersinnehav', '', false),
    (cid, '1351', 'Andelar i noterade företag', '', false),
    (cid, '1352', 'Andra andelar', '', false),
    (cid, '1353', 'Andelar i bostadsrättsföreningar', '', false),
    (cid, '1354', 'Obligationer', '', false),
    (cid, '1356', 'Andelar i ekonomiska föreningar', '', false),
    (cid, '1357', 'Andelar i handelsbolag', '', true),
    (cid, '1358', 'Ackumulerade nedskrivningar av andra långfristiga värdepappersinnehav', '', false),
    (cid, '1360', 'Lån till delägare eller närstående, långfristig del', '', false),
    (cid, '1369', 'Ackumulerade nedskrivningar av lån till delägare eller närstående, långfristig del', '', false),
    (cid, '1370', 'Uppskjuten skattefordran', '', false),
    (cid, '1380', 'Andra långfristiga fordringar', '', false),
    (cid, '1381', 'Långfristiga reversfordringar', '', false),
    (cid, '1382', 'Långfristiga fordringar hos anställda', '', true),
    (cid, '1383', 'Lämnade depositioner, långfristiga', '', false),
    (cid, '1384', 'Derivat', '', false),
    (cid, '1385', 'Kapitalförsäkring', '', false),
    (cid, '1386', 'Förutbetalda leasingavgifter, långfristig del', '', false),
    (cid, '1387', 'Långfristiga kontraktsfordringar', '', false),
    (cid, '1388', 'Långfristiga kundfordringar', '', true),
    (cid, '1389', 'Ackumulerade nedskrivningar av andra långfristiga fordringar', '', false),
    (cid, '1410', 'Lager av råvaror', '', false),
    (cid, '1419', 'Förändring av lager av råvaror', '', false),
    (cid, '1420', 'Lager av tillsatsmaterial och förnödenheter', '', false),
    (cid, '1429', 'Förändring av lager av tillsatsmaterial och förnödenheter', '', false),
    (cid, '1440', 'Produkter i arbete', '', false),
    (cid, '1449', 'Förändring av produkter i arbete', '', false),
    (cid, '1450', 'Lager av färdiga varor', '', false),
    (cid, '1459', 'Förändring av lager av färdiga varor', '', false),
    (cid, '1460', 'Lager av handelsvaror', '', false),
    (cid, '1465', 'Lager av varor VMB', '', false),
    (cid, '1466', 'Nedskrivning av varor VMB', '', false),
    (cid, '1467', 'Lager av varor VMB förenklad', '', false),
    (cid, '1469', 'Förändring av lager av handelsvaror', '', false),
    (cid, '1470', 'Pågående arbeten', '', true),
    (cid, '1471', 'Pågående arbeten, nedlagda kostnader', '', false),
    (cid, '1478', 'Pågående arbeten, fakturering', '', false),
    (cid, '1479', 'Förändring av pågående arbeten', '', false),
    (cid, '1480', 'Förskott för varor och tjänster', '', false),
    (cid, '1481', 'Remburser', '', false),
    (cid, '1489', 'Övriga förskott till leverantörer', '', false),
    (cid, '1490', 'Övriga lagertillgångar', '', false),
    (cid, '1491', 'Lager av värdepapper', '', false),
    (cid, '1492', 'Lager av fastigheter', '', false),
    (cid, '1493', 'Djur som klassificeras som omsättningstillgång', '', false),
    (cid, '1510', 'Kundfordringar', '', true),
    (cid, '1511', 'Kundfordringar', '', false),
    (cid, '1512', 'Belånade kundfordringar (factoring)', '', false),
    (cid, '1513', 'Kundfordringar – delad faktura', '', false),
    (cid, '1516', 'Tvistiga kundfordringar', '', false),
    (cid, '1518', 'Ej reskontraförda kundfordringar', '', true),
    (cid, '1519', 'Nedskrivning av kundfordringar', '', true),
    (cid, '1520', 'Växelfordringar', '', false),
    (cid, '1525', 'Osäkra växelfordringar', '', false),
    (cid, '1529', 'Nedskrivning av växelfordringar', '', false),
    (cid, '1530', 'Kontraktsfordringar', '', false),
    (cid, '1531', 'Kontraktsfordringar', '', false),
    (cid, '1532', 'Belånade kontraktsfordringar', '', false),
    (cid, '1536', 'Tvistiga kontraktsfordringar', '', false),
    (cid, '1539', 'Nedskrivning av kontraktsfordringar', '', false),
    (cid, '1549', 'Nedskrivning av ej reskontraförda kundfordringar', '', true),
    (cid, '1550', 'Konsignationsfordringar', '', false),
    (cid, '1560', 'Kundfordringar hos koncernföretag', '', false),
    (cid, '1561', 'Kundfordringar hos moderföretag', '', false),
    (cid, '1562', 'Kundfordringar hos dotterföretag', '', false),
    (cid, '1563', 'Kundfordringar hos andra koncernföretag', '', false),
    (cid, '1568', 'Ej reskontraförda kundfordringar hos koncernföretag', '', false),
    (cid, '1569', 'Nedskrivning av kundfordringar hos koncernföretag', '', false),
    (cid, '1570', 'Kundfordringar hos intresseftg, gemen styrda ftg och övr ftg som det finns ett ägarintr i', '', false),
    (cid, '1571', 'Kundfordringar hos intresseföretag', '', false),
    (cid, '1572', 'Kundfordringar hos gemensamt styrda företag', '', false),
    (cid, '1573', 'Kundfordringar hos övriga företag som det finns ett ägarintresse i', '', false),
    (cid, '1580', 'Fordringar för kontokort och kuponger', '', false),
    (cid, '1599', 'Övriga kortfristiga fordringar för kunder', '', false),
    (cid, '1610', 'Kortfristiga fordringar hos anställda', '', false),
    (cid, '1611', 'Reseförskott', '', false),
    (cid, '1612', 'Kassaförskott', '', false),
    (cid, '1613', 'Övriga förskott', '', false),
    (cid, '1614', 'Tillfälliga lån till anställda', '', false),
    (cid, '1619', 'Övriga fordringar hos anställda', '', false),
    (cid, '1620', 'Upparbetad men ej fakturerad intäkt', '', false),
    (cid, '1630', 'Avräkning för skatter och avgifter (skattekonto)', '', true),
    (cid, '1640', 'Skattefordringar', '', true),
    (cid, '1650', 'Momsfordran', '', true),
    (cid, '1660', 'Kortfristiga fordringar hos koncernföretag', '', false),
    (cid, '1661', 'Kortfristiga fordringar hos moderföretag', '', false),
    (cid, '1662', 'Kortfristiga fordringar hos dotterföretag', '', false),
    (cid, '1663', 'Kortfristiga fordringar hos andra koncernföretag', '', false),
    (cid, '1670', 'Kortfristiga fordr hos intresseftg, gemen styrda ftg och övr ftg som det finns ett ägarintr i', '', false),
    (cid, '1671', 'Kortfristiga fordringar hos intresseföretag', '', false),
    (cid, '1672', 'Kortfristiga fordringar hos gemensamt styrda företag', '', false),
    (cid, '1673', 'Kortfristiga fordringar hos övriga företag som det finns ett ägarintresse i', '', false),
    (cid, '1680', 'Andra kortfristiga fordringar', '', false),
    (cid, '1681', 'Utlägg för kunder', '', false),
    (cid, '1682', 'Kortfristiga lånefordringar', '', false),
    (cid, '1683', 'Derivat', '', false),
    (cid, '1684', 'Kortfristiga fordringar hos leverantörer', '', false),
    (cid, '1685', 'Kortfristiga fordringar hos delägare eller närstående', '', false),
    (cid, '1686', 'Fordringar för kontokort och kuponger', '', false),
    (cid, '1687', 'Kortfristig del av långfristiga fordringar', '', false),
    (cid, '1688', 'Fordran arbetsmarknadsförsäkringar', '', false),
    (cid, '1689', 'Övriga kortfristiga fordringar', '', false),
    (cid, '1690', 'Fordringar för tecknat men ej inbetalt aktiekapital', '', false),
    (cid, '1700', 'Förutbetalda kostnader/interimsfordringar', '', true),
    (cid, '1710', 'Förutbetalda hyreskostnader', '', false),
    (cid, '1720', 'Förutbetalda leasingavgifter', '', false),
    (cid, '1730', 'Förutbetalda försäkringspremier', '', false),
    (cid, '1740', 'Förutbetalda räntekostnader', '', false),
    (cid, '1750', 'Upplupna hyresintäkter', '', false),
    (cid, '1760', 'Upplupna ränteintäkter', '', false),
    (cid, '1770', 'Tillgångar av kostnadsnatur', '', false),
    (cid, '1780', 'Upplupna avtalsintäkter', '', false),
    (cid, '1790', 'Övriga förutbetalda kostnader och upplupna intäkter', '', true),
    (cid, '1810', 'Andelar i börsnoterade företag', '', false),
    (cid, '1820', 'Obligationer', '', false),
    (cid, '1830', 'Konvertibla skuldebrev', '', false),
    (cid, '1860', 'Andelar i koncernföretag, kortfristigt', '', false),
    (cid, '1869', 'Nedskrivning av andelar i koncernföretag', '', false),
    (cid, '1880', 'Andra kortfristiga placeringar', '', false),
    (cid, '1886', 'Derivat', '', false),
    (cid, '1889', 'Andelar i övriga företag', '', false),
    (cid, '1890', 'Nedskrivning av kortfristiga placeringar', '', false),
    (cid, '1910', 'Kassa', '', true),
    (cid, '1911', 'Huvudkassa', '', false),
    (cid, '1912', 'Kassa 2', '', false),
    (cid, '1913', 'Kassa 3', '', false),
    (cid, '1920', 'PlusGiro', '', true),
    (cid, '1930', 'Företagskonto', '', true),
    (cid, '1940', 'Övriga bankkonton', '', true),
    (cid, '1950', 'Bankcertifikat', '', false),
    (cid, '1960', 'Koncernkonto moderföretag', '', false),
    (cid, '1970', 'Särskilda bankkonton', '', false),
    (cid, '1972', 'Upphovsmannakonto', '', false),
    (cid, '1973', 'Skogskonto', '', false),
    (cid, '1974', 'Spärrade bankmedel', '', false),
    (cid, '1979', 'Övriga särskilda bankkonton', '', false),
    (cid, '1980', 'Valutakonton', '', true),
    (cid, '1990', 'Redovisningsmedel', '', false),
    (cid, '2010', 'Eget kapital, delägare 1', '', false),
    (cid, '2011', 'Egna varuuttag', '', false),
    (cid, '2012', 'Avräkning för skatter och avgifter (skattekonto)', '', false),
    (cid, '2013', 'Övriga egna uttag', '', false),
    (cid, '2016', 'Förändring i fond för verkligt värde', '', false),
    (cid, '2017', 'Årets kapitaltillskott', '', false),
    (cid, '2018', 'Övriga egna insättningar', '', true),
    (cid, '2019', 'Årets resultat, delägare 1', '', false),
    (cid, '2029', 'Årets resultat, delägare 2', '', false),
    (cid, '2050', 'Avsättning till expansionsfond', '', false),
    (cid, '2060', 'Eget kapital i ideella föreningar, stiftelser och registrerade trossamfund', '', false),
    (cid, '2061', 'Kapital/stiftelsekapital/grundkapital', '', false),
    (cid, '2064', 'Ackumulerat realisationsresultat', '', false),
    (cid, '2065', 'Fond för verkligt värde', '', false),
    (cid, '2066', 'Värdesäkringsfond', '', false),
    (cid, '2067', 'Balanserat', '', false),
    (cid, '2068', 'Överskott eller underskott från föregående år', '', false),
    (cid, '2069', 'Årets resultat', '', false),
    (cid, '2070', 'Ändamålsbestämda medel', '', false),
    (cid, '2071', 'Ändamål 1', '', false),
    (cid, '2072', 'Ändamål 2', '', false),
    (cid, '2080', 'Bundet eget kapital', '', false),
    (cid, '2081', 'Aktiekapital', '', true),
    (cid, '2082', 'Ej registrerat aktiekapital', '', false),
    (cid, '2083', 'Medlemsinsatser', '', false),
    (cid, '2084', 'Förlagsinsatser', '', false),
    (cid, '2085', 'Uppskrivningsfond', '', false),
    (cid, '2086', 'Reservfond', '', true),
    (cid, '2087', 'Bunden överkursfond', '', true),
    (cid, '2088', 'Fond för yttre underhåll', '', false),
    (cid, '2089', 'Fond för utvecklingsutgifter', '', false),
    (cid, '2090', 'Fritt eget kapital', '', false),
    (cid, '2091', 'Balanserad vinst eller förlust', '', true),
    (cid, '2092', 'Mottagna/lämnade koncernbidrag', '', false),
    (cid, '2093', 'Erhållna aktieägartillskott', '', true),
    (cid, '2094', 'Egna aktier', '', false),
    (cid, '2095', 'Fusionsresultat', '', false),
    (cid, '2096', 'Fond för verkligt värde', '', false),
    (cid, '2097', 'Fri överkursfond', '', false),
    (cid, '2098', 'Vinst eller förlust från föregående år', '', true),
    (cid, '2099', 'Årets resultat', '', true),
    (cid, '2110', 'Periodiseringsfonder', '', true),
    (cid, '2113', 'Periodiseringsfond vid 2013 års taxering', '', false),
    (cid, '2120', 'Periodiseringsfond 2020', '', false),
    (cid, '2121', 'Periodiseringsfond 2021', '', true),
    (cid, '2122', 'Periodiseringsfond 2022', '', true),
    (cid, '2123', 'Periodiseringsfond 2023', '', false),
    (cid, '2124', 'Periodiseringsfond 2024', '', false),
    (cid, '2125', 'Periodiseringsfond 2025', '', true),
    (cid, '2126', 'Periodiseringsfond 2026', '', true),
    (cid, '2127', 'Periodiseringsfond 2027', '', true),
    (cid, '2129', 'Periodiseringsfond 2019', '', true),
    (cid, '2130', 'Periodiseringsfond 2020 – nr 2', '', true),
    (cid, '2131', 'Periodiseringsfond 2021 – nr 2', '', true),
    (cid, '2132', 'Periodiseringsfond 2022 – nr 2', '', true),
    (cid, '2133', 'Periodiseringsfond 2023 – nr 2', '', true),
    (cid, '2134', 'Periodiseringsfond 2024 – nr 2', '', true),
    (cid, '2135', 'Periodiseringsfond 2025 – nr 2', '', true),
    (cid, '2136', 'Periodiseringsfond 2026 – nr 2', '', true),
    (cid, '2137', 'Periodiseringsfond 2027 – nr 2', '', true),
    (cid, '2139', 'Periodiseringsfond 2019 – nr 2', '', true),
    (cid, '2150', 'Ackumulerade överavskrivningar', '', true),
    (cid, '2151', 'Ackumulerade överavskrivningar på immateriella anläggningstillgångar', '', false),
    (cid, '2152', 'Ackumulerade överavskrivningar på byggnader och markanläggningar', '', false),
    (cid, '2153', 'Ackumulerade överavskrivningar på maskiner respektive inventarier', '', false),
    (cid, '2160', 'Ersättningsfond', '', false),
    (cid, '2161', 'Ersättningsfond maskiner och inventarier', '', false),
    (cid, '2162', 'Ersättningsfond byggnader och markanläggningar', '', false),
    (cid, '2164', 'Ersättningsfond för djurlager i jordbruk och renskötsel', '', false),
    (cid, '2180', 'Obeskattade intäkter', '', false),
    (cid, '2181', 'Obeskattade upphovsmannaintäkter', '', false),
    (cid, '2185', 'Obeskattade skogsintäkter', '', false),
    (cid, '2190', 'Övriga obeskattade reserver', '', false),
    (cid, '2191', 'Skillnad mellan bokförd och faktisk pensionsskuld', '', false),
    (cid, '2196', 'Lagerreserv', '', false),
    (cid, '2199', 'Övriga obeskattade reserver', '', false),
    (cid, '2210', 'Avsättningar för pensioner enligt tryggandelagen', '', false),
    (cid, '2220', 'Avsättningar för garantier', '', false),
    (cid, '2230', 'Övriga avsättningar för pensioner och liknande förpliktelser', '', false),
    (cid, '2240', 'Avsättningar för uppskjutna skatter', '', false),
    (cid, '2250', 'Övriga avsättningar för skatter', '', false),
    (cid, '2252', 'Avsättningar för tvistiga skatter', '', false),
    (cid, '2253', 'Avsättningar särskild löneskatt, deklarationspost', '', false),
    (cid, '2259', 'Avsättningar för övriga skatter', '', false),
    (cid, '2290', 'Övriga avsättningar', '', false),
    (cid, '2310', 'Obligations- och förlagslån', '', false),
    (cid, '2320', 'Konvertibla lån och liknande', '', false),
    (cid, '2321', 'Konvertibla lån', '', false),
    (cid, '2322', 'Lån förenade med optionsrätt', '', false),
    (cid, '2323', 'Vinstandelslån', '', false),
    (cid, '2324', 'Kapitalandelslån', '', false),
    (cid, '2330', 'Kontokredit', '', false),
    (cid, '2335', 'Beviljad checkräkningskredit 1', '', false),
    (cid, '2336', 'Beviljad checkräkningskredit 2', '', false),
    (cid, '2340', 'Byggnadskreditiv', '', false),
    (cid, '2350', 'Andra långfristiga skulder till kreditinstitut', '', false),
    (cid, '2351', 'Fastighetslån, långfristig del', '', false),
    (cid, '2355', 'Långfristiga lån i utländsk valuta från kreditinstitut', '', false),
    (cid, '2359', 'Övriga långfristiga lån från kreditinstitut', '', false),
    (cid, '2360', 'Långfristiga skulder till koncernföretag', '', false),
    (cid, '2361', 'Långfristiga skulder till moderföretag', '', false),
    (cid, '2362', 'Långfristiga skulder till dotterföretag', '', false),
    (cid, '2363', 'Långfristiga skulder till andra koncernföretag', '', false),
    (cid, '2370', 'Långfristiga skulder till intresseftg, gemen styrda ftg och övr ftg som det finns ett ägarintr i', '', false),
    (cid, '2371', 'Långfristiga skulder till intresseföretag', '', false),
    (cid, '2372', 'Långfristiga skulder till gemensamt styrda företag', '', false),
    (cid, '2373', 'Långfristiga skulder till övriga företag som det finns ett ägarintresse i', '', false),
    (cid, '2390', 'Övriga långfristiga skulder', '', true),
    (cid, '2391', 'Avbetalningskontrakt, långfristig del', '', false),
    (cid, '2392', 'Villkorliga långfristiga skulder', '', false),
    (cid, '2393', 'Lån från närstående personer, långfristig del', '', false),
    (cid, '2394', 'Långfristiga leverantörskrediter', '', false),
    (cid, '2395', 'Andra långfristiga lån i utländsk valuta', '', false),
    (cid, '2396', 'Derivat', '', false),
    (cid, '2397', 'Mottagna depositioner, långfristiga', '', false),
    (cid, '2399', 'Övriga långfristiga skulder', '', true),
    (cid, '2410', 'Andra kortfristiga låneskulder till kreditinstitut', '', false),
    (cid, '2411', 'Kortfristiga lån från kreditinstitut', '', false),
    (cid, '2412', 'Byggnadskreditiv, kortfristig del', '', false),
    (cid, '2417', 'Kortfristig del av långfristiga skulder till kreditinstitut', '', false),
    (cid, '2419', 'Övriga kortfristiga skulder till kreditinstitut', '', false),
    (cid, '2420', 'Förskott från kunder', '', true),
    (cid, '2421', 'Ej inlösta presentkort', '', false),
    (cid, '2429', 'Övriga förskott från kunder', '', false),
    (cid, '2430', 'Pågående arbeten', '', false),
    (cid, '2431', 'Pågående arbeten, fakturering', '', false),
    (cid, '2438', 'Pågående arbeten, nedlagda kostnader', '', false),
    (cid, '2439', 'Beräknad förändring av pågående arbeten', '', false),
    (cid, '2440', 'Leverantörsskulder', '', true),
    (cid, '2443', 'Konsignationsskulder', '', false),
    (cid, '2445', 'Tvistiga leverantörsskulder', '', false),
    (cid, '2448', 'Ej reskontraförda leverantörsskulder', '', true),
    (cid, '2450', 'Fakturerad men ej upparbetad intäkt', '', false),
    (cid, '2460', 'Leverantörsskulder till koncernföretag', '', false),
    (cid, '2461', 'Leverantörsskulder till moderföretag', '', false),
    (cid, '2462', 'Leverantörsskulder till dotterföretag', '', false),
    (cid, '2463', 'Leverantörsskulder till andra koncernföretag', '', false),
    (cid, '2470', 'Leverantörsskulder till intresseftg, gemen styrda ftg och övr ftg som det finns ett ägarintr i', '', false),
    (cid, '2471', 'Leverantörsskulder till intresseföretag', '', false),
    (cid, '2472', 'Leverantörsskulder till gemensamt styrda företag', '', false),
    (cid, '2473', 'Leverantörsskulder till övriga företag som det finns ett ägarintresse i', '', false),
    (cid, '2480', 'Kontokredit, kortfristig', '', false),
    (cid, '2490', 'Övriga kortfristiga skulder till kreditinstitut, kunder och leverantörer', '', false),
    (cid, '2491', 'Avräkning spelarrangörer', '', false),
    (cid, '2492', 'Växelskulder', '', false),
    (cid, '2499', 'Andra övriga kortfristiga skulder', '', true),
    (cid, '2510', 'Skatteskulder', '', true),
    (cid, '2512', 'Beräknad inkomstskatt', '', false),
    (cid, '2513', 'Beräknad fastighetsskatt/fastighetsavgift', '', false),
    (cid, '2514', 'Beräknad särskild löneskatt på pensionskostnader', '', false),
    (cid, '2515', 'Beräknad avkastningsskatt', '', false),
    (cid, '2516', 'Moms', '', false),
    (cid, '2517', 'Beräknad utländsk skatt', '', false),
    (cid, '2518', 'Betald F-skatt', '', true),
    (cid, '2611', 'Utgående moms på försäljning inom Sverige, 25%', '10-25%', true),
    (cid, '2612', 'Utgående moms på egna uttag, 25%', '10-25%', true),
    (cid, '2613', 'Utgående moms för uthyrning, 25%', '10-25%', false),
    (cid, '2614', 'Utgående moms, omvänd betalningsskyldighet, 25 %', '30-25%', true),
    (cid, '2615', 'Utgående moms import av varor 25%', '60-25%', true),
    (cid, '2616', 'Utgående moms VMB 25%', '10-25%', false),
    (cid, '2618', 'Vilande utgående moms, 25%', '', false),
    (cid, '2619', 'Utgående moms på försäljning inom EU, OSS', '', true),
    (cid, '2620', 'Utgående moms, 12%', '', false),
    (cid, '2621', 'Utgående moms på försäljning inom Sverige, 12%', '11-12%', true),
    (cid, '2622', 'Utgående moms på egna uttag, 12%', '11-12%', false),
    (cid, '2623', 'Utgående moms för uthyrning, 12%', '11-12%', false),
    (cid, '2624', 'Utgående moms, omvänd betalningsskyldighet, 12 %', '31-12%', true),
    (cid, '2625', 'Utgående moms import av varor 12%', '61-12%', false),
    (cid, '2626', 'Utgående moms VMB 12%', '11-12%', false),
    (cid, '2628', 'Vilande utgående moms, 12%', '', false),
    (cid, '2631', 'Utgående moms på försäljning inom Sverige, 6%', '12-6%', true),
    (cid, '2632', 'Utgående moms på egna uttag, 6%', '12-6%', false),
    (cid, '2633', 'Utgående moms för uthyrning, 6%', '12-6%', false),
    (cid, '2634', 'Utgående moms, omvänd betalningsskyldighet, 6 %', '32-6%', true),
    (cid, '2635', 'Utgående moms import av varor 6%', '62-6%', false),
    (cid, '2636', 'Utgående moms VMB 6%', '12-6%', false),
    (cid, '2638', 'Vilande utgående moms, 6%', '', false),
    (cid, '2640', 'Ingående moms', '48', false),
    (cid, '2641', 'Debiterad ingående moms', '48', true),
    (cid, '2642', 'Debiterad ingående moms i anslutning till frivillig betalningsskyldighet', '48', false),
    (cid, '2645', 'Beräknad ingående moms på förvärv från utlandet', '48', true),
    (cid, '2646', 'Ingående moms på uthyrning', '48', false),
    (cid, '2647', 'Ingående moms, omvänd betalningsskyldighet varor och tjänster i Sverige', '48', true),
    (cid, '2648', 'Vilande ingående moms', '', false),
    (cid, '2649', 'Ingående moms, blandad verksamhet', '', false),
    (cid, '2650', 'Redovisningskonto för moms', '', true),
    (cid, '2660', 'Särskilda punktskatter', '', false),
    (cid, '2661', 'Reklamskatt', '', false),
    (cid, '2669', 'Övriga punktskatter', '', false),
    (cid, '2670', 'Utgående moms på försäljning inom EU, OSS', '', false),
    (cid, '2710', 'Personalskatt', '', true),
    (cid, '2730', 'Lagstadgade sociala avgifter och särskild löneskatt', '', true),
    (cid, '2731', 'Avräkning lagstadgade sociala avgifter', '', true),
    (cid, '2732', 'Avräkning särskild löneskatt', '', true),
    (cid, '2740', 'Avtalade sociala avgifter', '', false),
    (cid, '2750', 'Utmätning i lön m.m.', '', false),
    (cid, '2760', 'Semestermedel', '', false),
    (cid, '2761', 'Avräkning semesterlöner', '', false),
    (cid, '2762', 'Semesterlönekassa', '', false),
    (cid, '2790', 'Övriga löneavdrag', '', true),
    (cid, '2791', 'Personalens intressekonto', '', false),
    (cid, '2792', 'Lönsparande', '', false),
    (cid, '2793', 'Gruppförsäkringspremier', '', false),
    (cid, '2794', 'Fackföreningsavgifter', '', true),
    (cid, '2795', 'Mätnings- och granskningsarvoden', '', false),
    (cid, '2799', 'Övriga löneavdrag', '', false),
    (cid, '2810', 'Avräkning för factoring och belånade kontraktsfordringar', '', false),
    (cid, '2811', 'Avräkning för factoring', '', false),
    (cid, '2812', 'Avräkning för belånade kontraksfordringar', '', false),
    (cid, '2820', 'Kortfristiga skulder till anställda', '', false),
    (cid, '2821', 'Löneskulder', '', false),
    (cid, '2822', 'Reseräkningar', '', false),
    (cid, '2823', 'Tantiem, gratifikationer', '', false),
    (cid, '2829', 'Övriga kortfristiga skulder till anställda', '', false),
    (cid, '2830', 'Avräkning för annans räkning', '', false),
    (cid, '2840', 'Kortfristiga låneskulder', '', false),
    (cid, '2841', 'Kortfristig del av långfristiga skulder', '', false),
    (cid, '2849', 'Övriga kortfristiga låneskulder', '', false),
    (cid, '2850', 'Avräkning för skatter och avgifter (skattekonto)', '', false),
    (cid, '2852', 'Anståndsbelopp för moms, arbetsgivaravgifter och personalskatt', '', false),
    (cid, '2860', 'Kortfristiga skulder till koncernföretag', '', false),
    (cid, '2861', 'Kortfristiga skulder till moderföretag', '', false),
    (cid, '2862', 'Kortfristiga skulder till dotterföretag', '', false),
    (cid, '2863', 'Kortfristiga skulder till andra koncernföretag', '', false),
    (cid, '2870', 'Kortfristiga skulder till intresseftg, gemen styrda ftg och övr ftg som det finns ett ägarintr i', '', false),
    (cid, '2871', 'Kortfristiga skulder till intresseföretag', '', false),
    (cid, '2872', 'Kortfristiga skulder till gemensamt styrda företag', '', false),
    (cid, '2873', 'Kortfristiga skulder till övriga företag som det finns ett ägarintresse i', '', false),
    (cid, '2880', 'Skuld erhållna bidrag', '', false),
    (cid, '2890', 'Övriga kortfristiga skulder', '', true),
    (cid, '2891', 'Skulder under indrivning', '', false),
    (cid, '2892', 'Inre reparationsfond/underhållsfond', '', false),
    (cid, '2893', 'Skulder till närstående personer, kortfristig del', '', false),
    (cid, '2895', 'Derivat (kortfristiga skulder)', '', false),
    (cid, '2896', 'Skuld till personal - dricks', '', false),
    (cid, '2897', 'Mottagna depositioner, kortfristiga', '', false),
    (cid, '2898', 'Outtagen vinstutdelning', '', false),
    (cid, '2899', 'Övriga kortfristiga skulder', '', false),
    (cid, '2910', 'Upplupna löner', '', true),
    (cid, '2911', 'Löneskulder', '', false),
    (cid, '2912', 'Ackordsöverskott', '', false),
    (cid, '2919', 'Övriga upplupna löner', '', false),
    (cid, '2920', 'Upplupna semesterlöner', '', true),
    (cid, '2930', 'Upplupna pensionskostnader', '', false),
    (cid, '2931', 'Upplupna pensionsutbetalningar', '', false),
    (cid, '2940', 'Upplupna lagstadgade sociala och andra avgifter', '', true),
    (cid, '2941', 'Beräknade upplupna lagstadgade sociala avgifter', '', true),
    (cid, '2942', 'Beräknad upplupen särskild löneskatt', '', false),
    (cid, '2943', 'Beräknad upplupen särskild löneskatt på pensionskostnader, deklarationspost', '', false),
    (cid, '2944', 'Beräknad upplupen avkastningsskatt på pensionskostnader', '', false),
    (cid, '2950', 'Upplupna avtalade sociala avgifter', '', true),
    (cid, '2951', 'Upplupna avtalade arbetsmarknadsförsäkringar', '', false),
    (cid, '2959', 'Upplupna avtalade pensionsförsäkringsavgifter, deklarationspost', '', true),
    (cid, '2960', 'Upplupna räntekostnader', '', false),
    (cid, '2970', 'Förutbetalda intäkter', '', false),
    (cid, '2971', 'Förutbetalda hyresintäkter', '', false),
    (cid, '2972', 'Förutbetalda medlemsavgifter', '', false),
    (cid, '2979', 'Övriga förutbetalda intäkter', '', false),
    (cid, '2980', 'Upplupna avtalskostnader', '', false),
    (cid, '2990', 'Övriga upplupna kostnader och förutbetalda intäkter', '', true),
    (cid, '2991', 'Beräknat arvode för bokslut', '', false),
    (cid, '2992', 'Beräknat arvode för revision', '', false),
    (cid, '2993', 'Ospecificerad skuld till leverantörer', '', false),
    (cid, '2995', 'Ej ankomna leverantörsfakturor', '', false),
    (cid, '2998', 'Övriga upplupna kostnader och förutbetalda intäkter', '', false),
    (cid, '2999', 'OBS-konto', '', true),
    (cid, '3000', 'Försäljning inom Sverige', '', false),
    (cid, '3001', 'Försäljning inom Sverige, 25 % moms', '05-25%', false),
    (cid, '3002', 'Försäljning inom Sverige, 12 % moms', '05-12%', false),
    (cid, '3003', 'Försäljning inom Sverige, 6 % moms', '05-6%', false),
    (cid, '3004', 'Försäljning inom Sverige, momsfri', '', false),
    (cid, '3020', 'Försäljning VMB varor', '', false),
    (cid, '3028', 'Positiv VM omföringskonto', '', false),
    (cid, '3030', 'Positiv VM 25%', '07-25%', false),
    (cid, '3041', 'Försäljn tjänst 25% sv', '05-25%', true),
    (cid, '3042', 'Försäljn tjänst 12% sv', '05-12%', true),
    (cid, '3043', 'Försäljn tjänst 6% sv', '05-6%', true),
    (cid, '3044', 'Försäljn tjänst sv momsfri', '42-0%', true),
    (cid, '3045', 'Försäljn tjänst utanför EG momsfri', '40-0%', true),
    (cid, '3046', 'Försäljn tjänst till EG 25%', '05-25%', true),
    (cid, '3048', 'Försäljn tjänst EG momsfri', '39-0%', true),
    (cid, '3051', 'Försäljn varor 25% sv', '05-25%', true),
    (cid, '3052', 'Försäljn varor 12% sv', '05-12%', true),
    (cid, '3053', 'Försäljn varor 6% sv', '05-6%', true),
    (cid, '3054', 'Försäljn varor sv momsfri', '42-0%', true),
    (cid, '3055', 'Försäljn varor utanför EG momsfri', '36-0%', true),
    (cid, '3056', 'Försäljn varor till EG 25% momspliktig', '05-25%', true),
    (cid, '3057', 'Treparts försäljn varor till EG 25%', '38-0%', true),
    (cid, '3058', 'Försäljn varor EG momsfri', '35-0%', true),
    (cid, '3059', 'Momspl uttag av fast.tj 25%', '06-25%', false),
    (cid, '3062', 'Förs varor närst företag', '05-25%', false),
    (cid, '3100', 'Försäljning köpta produkter', '05-25%', false),
    (cid, '3105', 'Försäljning varor till land utanför EU', '36-0%', false),
    (cid, '3106', 'Försäljning varor till annat EU-land, momspliktig', '', false),
    (cid, '3108', 'Försäljning varor till annat EU-land, momsfri', '35-0%', false),
    (cid, '3109', 'Försäljning varor till annat EU-land, OSS', '', true),
    (cid, '3200', 'Försäljning VMB och omvänd moms', '', false),
    (cid, '3211', 'Försäljning positiv VMB 25 %', '', false),
    (cid, '3212', 'Försäljning negativ VMB 25 %', '', false),
    (cid, '3231', 'Försäljning inom byggsektorn, omvänd skattskyldighet moms', '41-0%', true),
    (cid, '3300', 'Försäljning av tjänster utanför Sverige', '40-0%', false),
    (cid, '3305', 'Försäljning tjänster till land utanför EU', '40-0%', false),
    (cid, '3308', 'Försäljning tjänster till annat EU-land', '', false),
    (cid, '3309', 'Försäljning tjänster till annat EU-land, OSS', '', true),
    (cid, '3320', 'Bingolotto', '', false),
    (cid, '3400', 'Försäljning, egna uttag', '', false),
    (cid, '3401', 'Egna uttag, momspliktiga, 25%', '06-25%', false),
    (cid, '3402', 'Egna uttag, momspliktiga, 12%', '06-12%', false),
    (cid, '3403', 'Egna uttag, momspliktiga, 6%', '06-6%', false),
    (cid, '3404', 'Egna uttag momsfria', '', false),
    (cid, '3500', 'Fakturerade kostnader (gruppkonto)', '', false),
    (cid, '3510', 'Fakturerat emballage', '05-25%', true),
    (cid, '3511', 'Fakturerat emballage', '05-25%', false),
    (cid, '3518', 'Returnerat emballage', '05-25%', false),
    (cid, '3520', 'Fakturerade frakter', '05-25%', true),
    (cid, '3521', 'Fakturerade frakter, EU-land', '35-0%', true),
    (cid, '3522', 'Fakturerade frakter, export', '36-0%', true),
    (cid, '3530', 'Fakturerade tull- och speditionskostnader m.m.', '36-0%', true),
    (cid, '3540', 'Faktureringsavgifter', '05-25%', true),
    (cid, '3541', 'Faktureringsavgifter, EU-land', '35-0%', true),
    (cid, '3542', 'Faktureringsavgifter, export', '36-0%', true),
    (cid, '3543', 'Faktureringavgift 12%', '05-12%', true),
    (cid, '3544', 'Faktureringavgift 6%', '05-6%', true),
    (cid, '3550', 'Fakturerade resekostnader', '05-25%', false),
    (cid, '3560', 'Fakturerade kostnader till koncernföretag', '', false),
    (cid, '3561', 'Fakturerade kostnader till moderföretag', '05-25%', false),
    (cid, '3562', 'Fakturerade kostnader till dotterföretag', '05-25%', false),
    (cid, '3563', 'Fakturerade kostnader till andra koncernföretag', '05-25%', false),
    (cid, '3570', 'Fakturerade kostnader till intresseftg, gemen styrda ftg och övr ftg som det finns ett ägarintr i', '', false),
    (cid, '3590', 'Övriga fakturerade kostnader', '05-25%', true),
    (cid, '3596', 'Påminnelseavgift', '42-0%', true),
    (cid, '3600', 'Rörelsens sidointäkter (gruppkonto)', '', false),
    (cid, '3610', 'Försäljning av material', '05-25%', false),
    (cid, '3611', 'Försäljning av råmaterial', '', false),
    (cid, '3612', 'Försäljning av skrot', '41-0%', false),
    (cid, '3613', 'Försäljning av förbrukningsmaterial', '', false),
    (cid, '3619', 'Försäljning av övrigt material', '', false),
    (cid, '3620', 'Tillfällig uthyrning av personal', '', false),
    (cid, '3630', 'Tillfällig uthyrning av transportmedel', '', false),
    (cid, '3670', 'Intäkter från värdepapper', '', false),
    (cid, '3671', 'Försäljning av värdepapper', '', false),
    (cid, '3672', 'Utdelning från värdepapper', '', false),
    (cid, '3679', 'Övriga intäkter från värdepapper', '', false),
    (cid, '3680', 'Management fees', '', false),
    (cid, '3690', 'Övriga sidointäkter', '05-25%', true),
    (cid, '3700', 'Intäktskorrigeringar (gruppkonto)', '', false),
    (cid, '3710', 'Ofördelade intäktsreduktioner', '', false),
    (cid, '3730', 'Lämnade rabatter', '', false),
    (cid, '3731', 'Lämnade kassarabatter', '', false),
    (cid, '3732', 'Lämnade mängdrabatter', '05-25%', false),
    (cid, '3736', 'Kassarabatter export utanför EG momsfri', '36-0%', false),
    (cid, '3737', 'Kassarabatter export inom EG momsfri', '35-0%', false),
    (cid, '3740', 'Öres- och kronutjämning', '', true),
    (cid, '3750', 'Punktskatter', '', false),
    (cid, '3751', 'Intäktsförda punktskatter (kreditkonto)', '', false),
    (cid, '3752', 'Skuldförda punktskatter (debetkonto)', '', false),
    (cid, '3790', 'Övriga intäktskorrigeringar', '', false),
    (cid, '3800', 'Aktiverat arbete för egen räkning (gruppkonto)', '', false),
    (cid, '3840', 'Aktiverat arbete (material)', '', false),
    (cid, '3850', 'Aktiverat arbete (omkostnader)', '', false),
    (cid, '3870', 'Aktiverat arbete (personal)', '', false),
    (cid, '3900', 'Övriga rörelseintäkter (gruppkonto)', '', false),
    (cid, '3901', 'Medlemsavgifter', '', false),
    (cid, '3910', 'Hyres- och arrendeintäkter', '', false),
    (cid, '3911', 'Hyresintäkter', '42-0%', false),
    (cid, '3912', 'Arrendeintäkter', '42-0%', false),
    (cid, '3913', 'Frivilligt momspliktiga hyresintäkter', '08-25%', false),
    (cid, '3914', 'Övriga momspliktiga hyresintäkter', '', false),
    (cid, '3920', 'Provisionsintäkter, licensintäkter och royalties', '', false),
    (cid, '3921', 'Provisionsintäkter', '42-0%', false),
    (cid, '3922', 'Licensintäkter och royalties', '', false),
    (cid, '3925', 'Franchiseintäkter', '', false),
    (cid, '3940', 'Orealiserade negativa/positiva värdeförändringar på säkringsinstrument', '42-0%', false),
    (cid, '3950', 'Återvunna, tidigare avskrivna kundfordringar', '42-0%', true),
    (cid, '3960', 'Valutakursvinster på fordringar och skulder av rörelsekaraktär', '', true),
    (cid, '3970', 'Vinst vid avyttring av immateriella och materiella anläggningstillgångar', '', true),
    (cid, '3971', 'Vinst vid avyttring av immateriella anläggningstillgångar', '', true),
    (cid, '3972', 'Vinst vid avyttring av byggnader och mark', '', false),
    (cid, '3973', 'Vinst vid avyttring av maskiner och inventarier', '', false),
    (cid, '3980', 'Erhållna offentliga bidrag', '', true),
    (cid, '3981', 'Erhållna EU-bidrag', '', false),
    (cid, '3985', 'Erhållna statliga bidrag', '42-0%', false),
    (cid, '3987', 'Erhållna kommunala bidrag', '42-0%', false),
    (cid, '3988', 'Erhållna offentliga bidrag för personal', '42-0%', false),
    (cid, '3989', 'Övriga erhållna offentliga bidrag', '42-0%', false),
    (cid, '3990', 'Övriga ersättningar, bidrag och intäkter', '42-0%', false),
    (cid, '3991', 'Konfliktersättning', '', false),
    (cid, '3992', 'Erhållna skadestånd', '', false),
    (cid, '3993', 'Erhållna donationer och gåvor', '', false),
    (cid, '3994', 'Försäkringsersättningar', '42-0%', false),
    (cid, '3995', 'Erhållet ackord på skulder av rörelsekaraktär', '', false),
    (cid, '3996', 'Erhållna reklambidrag', '42-0%', false),
    (cid, '3997', 'Sjuklöneersättning', '42-0%', false),
    (cid, '3998', 'Återbäring av överskott från försäkringsföretag', '', false),
    (cid, '3999', 'Övriga rörelseintäkter', '', false),
    (cid, '4000', 'Inköp av handelsvaror (gruppkonto)', '', true),
    (cid, '4010', 'Inköp av handelsvaror i Sverige', '', false),
    (cid, '4020', 'Inköp VMB varor', '', false),
    (cid, '4028', 'Negativ VM omföringskonto', '', false),
    (cid, '4030', 'Negativ VM', '', false),
    (cid, '4041', 'Inköpta tjänster i Sverige, omvänd skattskyldighet, moms 25%', '24-25%', false),
    (cid, '4042', 'Inköpta tjänster i Sverige, omvänd skattskyldighet, moms 12%', '24-12%', false),
    (cid, '4043', 'Inköpta tjänster i Sverige, omvänd skattskyldighet, moms 6% ', '24-6%', false),
    (cid, '4048', 'Inköp guldtackor/guldmynt', '', true),
    (cid, '4055', 'Trepartsförv varor fr EG', '37-0%', false),
    (cid, '4056', 'Inköp varor 25% EU', '20-25%', true),
    (cid, '4057', 'Inköp varor 12% EU', '20-12%', true),
    (cid, '4058', 'Inköp varor 6% EU', '20-6%', true),
    (cid, '4059', 'Inköp varor EU momsfri', '', true),
    (cid, '4060', 'Inköp av handelsvaror i Sverige, omvänd betalningsskyldighet', '', false),
    (cid, '4065', 'Inköp av handelsvaror i Sverige, omvänd betalningsskyldighet, 25 % moms', '23-25%', false),
    (cid, '4066', 'Inköp av handelsvaror i Sverige, omvänd betalningsskyldighet, 12 % moms', '23-12%', false),
    (cid, '4067', 'Inköp av handelsvaror i Sverige, omvänd betalningsskyldighet, 6 % moms', '23-6%', false),
    (cid, '4070', 'Inköp av handelsvaror från annat EU-land', '', false),
    (cid, '4075', 'Inköp av handelsvaror från annat EU-land, 25 % moms', '20-25%', false),
    (cid, '4076', 'Inköp av handelsvaror från annat EU-land, 12 % moms', '20-12%', false),
    (cid, '4077', 'Inköp av handelsvaror från annat EU-land, 6 % moms', '20-6%', false),
    (cid, '4078', 'Inköp av handelsvaror från annat EU-land, momsfri', '', false),
    (cid, '4080', 'Import av handelsvaror', '', false),
    (cid, '4085', 'Import av handelsvaror, 25 % moms', '50-25%', false),
    (cid, '4086', 'Import av handelsvaror, 12 % moms', '50-12%', false),
    (cid, '4087', 'Import av handelsvaror, 6 % moms', '50-6%', false),
    (cid, '4090', 'Erhållna rabatter (Handelsvaror)', '', true),
    (cid, '4091', 'Erhållna kassarabatter (Handelsvaror)', '', false),
    (cid, '4092', 'Erhållna mängdrabatter (inkl. bonus) (Handelsvaror)', '', false),
    (cid, '4099', 'Övriga reduktioner av inköpspriser (Handelsvaror)', '', false),
    (cid, '4100', 'Kostn uthyrn lokal sk.pl', '', false),
    (cid, '4200', 'Sålda handelsvaror VMB (gruppkonto)', '', false),
    (cid, '4210', 'Sålda handelsvaror VMB', '', false),
    (cid, '4211', 'Sålda handelsvaror positiv VMB 25 %', '', false),
    (cid, '4212', 'Sålda handelsvaror negativ VMB 25 %', '', false),
    (cid, '4300', 'Inköp av råvaror och material i Sverige (gruppkonto)', '', true),
    (cid, '4310', 'Inköp av råvaror och material i Sverige', '', false),
    (cid, '4400', 'Inköp av råvaror och material, tjänster m.m. i Sverige, omvänd betalningsskyldighet (gruppkonto)', '', true),
    (cid, '4410', 'Inköp av råvaror och material i Sverige, omvänd betalningsskyldighet', '', false),
    (cid, '4415', 'Inköpta varor i Sverige, omvänd betalningsskyldighet, 25 %', '23-25%', true),
    (cid, '4416', 'Inköpta varor i Sverige, omvänd betalningsskyldighet, 12 %', '23-12%', true),
    (cid, '4417', 'Inköpta varor i Sverige, omvänd betalningsskyldighet, 6 %', '23-6%', true),
    (cid, '4420', 'Inköp av tjänster i Sverige, omvänd betalningsskyldighet', '', false),
    (cid, '4425', 'Inköp av tjänster i Sverige, omvänd betalningsskyldighet, 25 % moms', '24-25%', false),
    (cid, '4426', 'Inköp av tjänster i Sverige, omvänd betalningsskyldighet, 12 % moms', '24-12%', false),
    (cid, '4427', 'Inköp av tjänster i Sverige, omvänd betalningsskyldighet, 6 % moms', '24-6%', false),
    (cid, '4500', 'Inköp av råvaror och material, tjänster m.m. från utlandet (gruppkonto)', '', true),
    (cid, '4510', 'Inköp av råvaror och material från annat EU-land', '', false),
    (cid, '4515', 'Inköp av råvaror och material från annat EU-land, 25 %', '20-25%', false),
    (cid, '4516', 'Inköp av råvaror och material från annat EU-land, 12 %', '20-12%', false),
    (cid, '4517', 'Inköp av råvaror och material från annat EU-land, 6 %', '20-6%', false),
    (cid, '4518', 'Inköp av råvaror och material från annat EU-land, momsfri', '', false),
    (cid, '4530', 'Inköp av tjänster m.m. från utlandet', '', false),
    (cid, '4531', 'Inköp av tjänster från ett land utanför EU, 25 % moms', '22-25%', true),
    (cid, '4532', 'Inköp av tjänster från ett land utanför EU, 12 % moms', '22-12%', true),
    (cid, '4533', 'Inköp av tjänster från ett land utanför EU, 6 % moms', '22-6%', true),
    (cid, '4535', 'Inköp av tjänster från annat EU-land, 25 %', '21-25%', false),
    (cid, '4536', 'Inköp av tjänster från annat EU-land, 12 %', '21-12%', false),
    (cid, '4537', 'Inköp av tjänster från annat EU-land, 6 %', '21-6%', false),
    (cid, '4538', 'Inköp av tjänster från annat EU-land, momsfri', '', false),
    (cid, '4540', 'Import av råvaror och material', '', false),
    (cid, '4545', 'Import av råvaror och material, 25 % moms', '50-25%', true),
    (cid, '4546', 'Import av råvaror och material, 12 % moms', '50-12%', true),
    (cid, '4547', 'Import av råvaror och material, 6 % moms', '50-6%', true),
    (cid, '4549', 'Motkonto beskattningsunderlag import', '', true),
    (cid, '4600', 'Inköp av tjänster, underentreprenader och legoarbeten i Sverige (gruppkonto)', '', true),
    (cid, '4610', 'Inköp av tjänster och underentreprenader', '', false),
    (cid, '4670', 'Inköp av legoarbeten', '', false),
    (cid, '4700', 'Reduktion av inköpspriser (gruppkonto)', '', true),
    (cid, '4730', 'Erhållna rabatter (Råvaror och förnödenheter)', '', false),
    (cid, '4731', 'Erhållna kassarabatter (Råvaror och förnödenheter)', '', false),
    (cid, '4732', 'Erhållna mängdrabatter (inkl. bonus) (Råvaror och förnödenheter)', '', false),
    (cid, '4739', 'Övriga reduktioner av inköpspriser (Råvaror och förnödenheter)', '', false),
    (cid, '4800', 'Andra produktionskostnader (gruppkonto)', '', true),
    (cid, '4810', 'Kostnader för energi (Råvaror och förnödenheter)', '', false),
    (cid, '4820', 'Kostnader för drivmedel (Råvaror och förnödenheter)', '', false),
    (cid, '4830', 'Kostnader för resor (Råvaror och förnödenheter)', '', false),
    (cid, '4840', 'Kostnader för hyra av utrustning (Råvaror och förnödenheter)', '', false),
    (cid, '4890', 'Övriga produktionskostnader (Råvaror och förnödenheter)', '', false),
    (cid, '4900', 'Förändring av lager (gruppkonto)', '', true),
    (cid, '4910', 'Förändring av lager av råvaror', '', false),
    (cid, '4920', 'Förändring av lager av tillsatsmaterial och förnödenheter', '', false),
    (cid, '4940', 'Förändring av produkter i arbete', '', false),
    (cid, '4944', 'Förändring av produkter i arbete, material och utlägg', '', false),
    (cid, '4945', 'Förändring av produkter i arbete, omkostnader', '', false),
    (cid, '4947', 'Förändring av produkter i arbete, personalkostnader', '', false),
    (cid, '4950', 'Förändring av lager av färdiga varor', '', false),
    (cid, '4960', 'Förändring av lager av handelsvaror', '', false),
    (cid, '4970', 'Förändring av pågående arbeten, nedlagda kostnader', '', false),
    (cid, '4974', 'Förändring av pågående arbeten, material och utlägg', '', false),
    (cid, '4975', 'Förändring av pågående arbeten, omkostnader', '', false),
    (cid, '4977', 'Förändring av pågående arbeten, personalkostnader', '', false),
    (cid, '4980', 'Förändring av lager av värdepapper (Handelsvaror)', '', false),
    (cid, '4981', 'Sålda värdepappers anskaffningsvärde (Handelsvaror)', '', false),
    (cid, '4987', 'Nedskrivning av värdepapper (Handelsvaror)', '', false),
    (cid, '4988', 'Återföring av nedskrivning av värdepapper (Handelsvaror)', '', false),
    (cid, '5000', 'Lokalkostnader (gruppkonto)', '', true),
    (cid, '5010', 'Lokalhyra', '', false),
    (cid, '5011', 'Hyra för kontorslokaler', '', false),
    (cid, '5012', 'Hyra för garage', '', false),
    (cid, '5013', 'Hyra för lagerlokaler', '', false),
    (cid, '5019', 'Övriga kostnader för lokalhyra', '', false),
    (cid, '5020', 'El', '', false),
    (cid, '5030', 'Värme', '', false),
    (cid, '5040', 'Vatten och avlopp', '', false),
    (cid, '5050', 'Lokaltillbehör', '', false),
    (cid, '5060', 'Städning och renhållning', '', false),
    (cid, '5061', 'Städning', '', false),
    (cid, '5062', 'Sophämtning', '', false),
    (cid, '5064', 'Snöröjning', '', false),
    (cid, '5065', 'Trädgårdsskötsel', '', false),
    (cid, '5069', 'Övriga kostnader för städning och underhåll', '', false),
    (cid, '5070', 'Reparation och underhåll av lokaler', '', false),
    (cid, '5090', 'Övriga lokalkostnader', '', false),
    (cid, '5100', 'Fastighetskostnader (gruppkonto)', '', false),
    (cid, '5110', 'Tomträttsavgäld/arrende', '', false),
    (cid, '5120', 'El', '', false),
    (cid, '5130', 'Värme', '', false),
    (cid, '5131', 'Uppvärmning', '', false),
    (cid, '5132', 'Sotning', '', false),
    (cid, '5139', 'Övriga kostnader för värme', '', false),
    (cid, '5140', 'Vatten och avlopp', '', false),
    (cid, '5160', 'Städning och renhållning', '', false),
    (cid, '5161', 'Städning', '', false),
    (cid, '5162', 'Sophämtning', '', false),
    (cid, '5164', 'Snöröjning', '', false),
    (cid, '5165', 'Trädgårdsskötsel', '', false),
    (cid, '5169', 'Övriga kostnader för städning och renhållning', '', false),
    (cid, '5170', 'Reparation och underhåll av fastighet', '', false),
    (cid, '5190', 'Övriga fastighetskostnader', '', false),
    (cid, '5191', 'Fastighetsskatt/fastighetsavgift', '', false),
    (cid, '5192', 'Fastighetsförsäkringspremier', '', false),
    (cid, '5193', 'Fastighetsskötsel och förvaltning', '', false),
    (cid, '5198', 'Övriga fastighetskostnader', '', false),
    (cid, '5200', 'Hyra av anläggningstillgångar (gruppkonto)', '', true),
    (cid, '5210', 'Hyra av maskiner och andra tekniska anläggningar, ej datorer och fordon', '', false),
    (cid, '5220', 'Hyra av inventarier och verktyg, ej datorer och fordon', '', false),
    (cid, '5250', 'Hyra av datorer', '', false),
    (cid, '5290', 'Hyra av övriga anläggningstillgångar, ej datorer och fordon', '', false),
    (cid, '5300', 'Energikostnader för drift (gruppkonto) (ej råvaror och förnödenheter)', '', false),
    (cid, '5310', 'El för drift (ej råvaror och förnödenheter)', '', false),
    (cid, '5320', 'Gas för drift (ej råvaror och förnödenheter)', '', false),
    (cid, '5330', 'Eldningsolja för drift (ej råvaror och förnödenheter)', '', false),
    (cid, '5340', 'Stenkol och koks för drift (ej råvaror och förnödenheter)', '', false),
    (cid, '5350', 'Torv, träkol, ved, m.m. för drift (ej råvaror och förnödenheter)', '', false),
    (cid, '5360', 'Bensin, fotogen och motorbrännolja för drift (ej råvaror och förnödenheter)', '', false),
    (cid, '5370', 'Fjärrvärme, kyla och ånga för drift (ej råvaror och förnödenheter)', '', false),
    (cid, '5380', 'Vatten för drift (ej råvaror och förnödenheter)', '', false),
    (cid, '5390', 'Övriga energikostnader för drift (ej råvaror och förnödenheter)', '', false),
    (cid, '5400', 'Förbrukningsinventarier och förbrukningsmaterial (gruppkonto)', '', true),
    (cid, '5410', 'Förbrukningsinventarier', '', true),
    (cid, '5411', 'Förbrukningsinv med en livslängd på mer än ett år', '', false),
    (cid, '5412', 'Förbrukningsinv med en livslängd om högst ett år', '', false),
    (cid, '5420', 'Programvaror', '', true),
    (cid, '5430', 'Transportinventarier', '', false),
    (cid, '5440', 'Förbrukningsemballage', '', false),
    (cid, '5460', 'Förbrukningsmaterial', '', true),
    (cid, '5480', 'Arbetskläder och skyddsmaterial', '', true),
    (cid, '5500', 'Reparation och underhåll (gruppkonto)', '', false),
    (cid, '5510', 'Reparation och underhåll av maskiner och andra tekniska anläggningar', '', false),
    (cid, '5520', 'Reparation och underhåll av inventarier, verktyg och datorer m.m.', '', false),
    (cid, '5530', 'Reparation och underhåll byggnads- och markinventarier', '', false),
    (cid, '5550', 'Reparation och underhåll av förbrukningsinventarier', '', false),
    (cid, '5580', 'Underhåll och tvätt av arbetskläder', '', false),
    (cid, '5590', 'Övriga kostnader för reparation och underhåll', '', false),
    (cid, '5600', 'Kostnader för transportmedel (gruppkonto)', '', true),
    (cid, '5610', 'Personbils- och mc-kostnader, m.m.', '', true),
    (cid, '5611', 'Drivmedel för personbilar, mc, m.m.', '', true),
    (cid, '5612', 'Försäkring och skatt för personbilar, mc, m.m.', '', true),
    (cid, '5613', 'Reparation och underhåll av personbilar, mc, m.m.', '', true),
    (cid, '5615', 'Leasing av personbilar, mc, m.m.', '', true),
    (cid, '5616', 'Trängselskatt personbilar', '', true),
    (cid, '5619', 'Övriga kostnader för personbilar och mc, m.m.', '', true),
    (cid, '5620', 'Lastbils- och busskostnader, m.m.', '', true),
    (cid, '5621', 'Drivmedel lastbilar och bussar', '', false),
    (cid, '5622', 'Försäkring och skatt lastbilar och bussar', '', false),
    (cid, '5623', 'Reparation och underhåll lastbilar och bussar', '', false),
    (cid, '5625', 'Leasing lastbilar och bussar', '', false),
    (cid, '5626', 'Trängselskatt lastbilar och bussar', '', false),
    (cid, '5629', 'Övriga lastbils- och busskostnader', '', false),
    (cid, '5630', 'Truckkostnader', '', true),
    (cid, '5631', 'Drivmedel truckar', '', false),
    (cid, '5632', 'Försäkring och skatt truckar', '', false),
    (cid, '5633', 'Reparation och underhåll truckar', '', false),
    (cid, '5635', 'Leasing truckar', '', false),
    (cid, '5639', 'Övriga kostnader för truckar', '', false),
    (cid, '5640', 'Kostnader för arbetsmaskiner', '', true),
    (cid, '5641', 'Drivmedel arbetsmaskiner', '', false),
    (cid, '5642', 'Försäkring och skatt arbetsmaskiner', '', false),
    (cid, '5643', 'Reparation och underhåll arbetsmaskiner', '', false),
    (cid, '5645', 'Leasing arbetsmaskiner', '', false),
    (cid, '5646', 'Trängselskatt arbetsmaskiner', '', false),
    (cid, '5649', 'Övriga kostnader för arbetsmaskiner', '', false),
    (cid, '5650', 'Traktorkostnader', '', true),
    (cid, '5651', 'Drivmedel traktorer', '', false),
    (cid, '5652', 'Försäkring och skatt traktorer', '', false),
    (cid, '5653', 'Reparation och underhåll traktorer', '', false),
    (cid, '5655', 'Leasing traktorer', '', false),
    (cid, '5656', 'Trängselskatt traktorer', '', false),
    (cid, '5659', 'Övriga kostnader för traktorer', '', false),
    (cid, '5670', 'Kostnader för fartyg och luftfartyg', '', true),
    (cid, '5671', 'Drivmedel fartyg och luftfartyg', '', false),
    (cid, '5672', 'Försäkring och skatt fartyg och luftfartyg', '', false),
    (cid, '5673', 'Reparation och underhåll fartyg och luftfartyg', '', false),
    (cid, '5675', 'Leasing fartyg och luftfartyg', '', false),
    (cid, '5679', 'Övriga kostnader för fartyg och luftfartyg', '', false),
    (cid, '5680', 'Kostnader för rälsfordon', '', false),
    (cid, '5681', 'Drivmedel rälsfordon', '', false),
    (cid, '5682', 'Försäkring och skatt rälsfordon', '', false),
    (cid, '5683', 'Reparation och underhåll rälsfordon', '', false),
    (cid, '5685', 'Leasing rälsfordon', '', false),
    (cid, '5689', 'Övriga kostnader för rälsfordon', '', false),
    (cid, '5690', 'Kostnader för övriga transportmedel', '', true),
    (cid, '5691', 'Drivmedel övriga transportmedel', '', false),
    (cid, '5692', 'Försäkring och skatt övriga transportmedel', '', false),
    (cid, '5693', 'Reparation och underhåll övriga transportmedel', '', false),
    (cid, '5695', 'Leasing övriga transportmedel', '', false),
    (cid, '5696', 'Trängselskatt övriga transportmedel', '', false),
    (cid, '5699', 'Övriga kostnader för övriga transportmedel', '', false),
    (cid, '5700', 'Frakter och transporter (gruppkonto)', '', true),
    (cid, '5710', 'Frakter och försäkringar vid varudistribution', '', false),
    (cid, '5711', 'Fraktkostnader', '', false),
    (cid, '5712', 'Försäkringar vid frakter', '', false),
    (cid, '5720', 'Tull- och speditionskostnader m.m.', '', false),
    (cid, '5721', 'Tullkostnader', '', false),
    (cid, '5722', 'Speditionskostnader', '', false),
    (cid, '5729', 'Övriga tull- och speditionskostnader m.m.', '', false),
    (cid, '5730', 'Arbetstransporter', '', false),
    (cid, '5790', 'Övriga kostnader för frakter och transporter', '', false),
    (cid, '5800', 'Resekostnader (gruppkonto)', '', true),
    (cid, '5810', 'Biljetter', '', false),
    (cid, '5820', 'Hyrbilskostnader', '', false),
    (cid, '5830', 'Kost och logi', '', false),
    (cid, '5831', 'Kost och logi i Sverige', '', false),
    (cid, '5832', 'Kost och logi i utlandet', '', false),
    (cid, '5890', 'Övriga resekostnader', '', false),
    (cid, '5900', 'Reklam och PR (gruppkonto)', '', true),
    (cid, '5910', 'Annonsering', '', false),
    (cid, '5920', 'Utomhus- och trafikreklam', '', false),
    (cid, '5930', 'Reklamtrycksaker och direktreklam', '', false),
    (cid, '5940', 'Utställningar och mässor', '', false),
    (cid, '5950', 'Butiksreklam och återförsäljarreklam', '', false),
    (cid, '5960', 'Varuprover, reklamgåvor, presentreklam och tävlingar', '', false),
    (cid, '5970', 'Film-, radio-, TV- och Internetreklam', '', false),
    (cid, '5980', 'Sponsring', '', false),
    (cid, '5981', 'Avdragsgill sponsring', '', false),
    (cid, '5982', 'Ej avdragsgill sponsring', '', false),
    (cid, '5990', 'Övriga kostnader för reklam och PR', '', false),
    (cid, '6000', 'Övriga försäljningskostnader (gruppkonto)', '', true),
    (cid, '6010', 'Kataloger, prislistor m.m.', '', false),
    (cid, '6020', 'Egna facktidskrifter', '', false),
    (cid, '6030', 'Speciella orderkostnader', '', false),
    (cid, '6040', 'Kontokortsavgifter', '', false),
    (cid, '6044', 'Avgift kortbetalning Webshop', '', true),
    (cid, '6050', 'Försäljningsprovisioner', '', false),
    (cid, '6055', 'Franchisekostnader', '', false),
    (cid, '6059', 'Övriga försäljningsprovisionskostnader', '', false),
    (cid, '6060', 'Kreditförsäljningskostnader', '', false),
    (cid, '6061', 'Kreditupplysning', '', false),
    (cid, '6062', 'Inkasso och KFM-avgifter', '', false),
    (cid, '6063', 'Kreditförsäkringspremier', '', false),
    (cid, '6064', 'Factoringavgifter', '', false),
    (cid, '6069', 'Övriga kreditförsäljningskostnader', '', false),
    (cid, '6070', 'Representation', '', false),
    (cid, '6071', 'Representation, avdragsgill', '', true),
    (cid, '6072', 'Representation, ej avdragsgill', '', true),
    (cid, '6080', 'Bankgarantier', '', false),
    (cid, '6090', 'Övriga försäljningskostnader', '', false),
    (cid, '6100', 'Kontorsmateriel och trycksaker (gruppkonto)', '', true),
    (cid, '6110', 'Kontorsmateriel', '', false),
    (cid, '6150', 'Trycksaker', '', false),
    (cid, '6200', 'Tele, data och post (gruppkonto)', '', true),
    (cid, '6210', 'Telekommunikation', '', false),
    (cid, '6211', 'Fast telefoni', '', false),
    (cid, '6212', 'Mobiltelefon', '', false),
    (cid, '6219', 'Övriga kostnader för telekommunikation', '', false),
    (cid, '6230', 'Datakommunikation', '', false),
    (cid, '6250', 'Porto', '', false),
    (cid, '6290', 'Övriga tele-, data- och postkostnader', '', false),
    (cid, '6300', 'Företagsförsäkringar och övriga riskkostnader (gruppkonto)', '', true),
    (cid, '6310', 'Företagsförsäkringar', '', false),
    (cid, '6320', 'Självrisker vid skada', '', false),
    (cid, '6330', 'Förluster i pågående arbeten', '', false),
    (cid, '6340', 'Lämnade skadestånd', '', false),
    (cid, '6341', 'Lämnade skadestånd, avdragsgilla', '', false),
    (cid, '6342', 'Lämnade skadestånd, ej avdragsgilla', '', false),
    (cid, '6350', 'Förluster på kundfordringar', '', true),
    (cid, '6351', 'Konstaterade förluster på kundfordringar', '', true),
    (cid, '6352', 'Befarade förluster på kundfordringar', '', true),
    (cid, '6358', 'Befarade förluster på kundfordringar, OSS', '', true),
    (cid, '6359', 'Konstaterade förluster på kundfordringar, OSS', '', true),
    (cid, '6360', 'Garantikostnader', '', false),
    (cid, '6361', 'Förändring av garantiavsättning', '', false),
    (cid, '6362', 'Faktiska garantikostnader', '', false),
    (cid, '6370', 'Kostnader för bevakning och larm', '', false),
    (cid, '6380', 'Förluster på övriga kortfristiga fordringar', '', false),
    (cid, '6390', 'Övriga riskkostnader', '', false),
    (cid, '6391', 'Övriga riskkostnader, avdragsgilla', '', false),
    (cid, '6392', 'Övriga riskkostnader, ej avdragsgilla', '', false),
    (cid, '6400', 'Förvaltningskostnader (gruppkonto)', '', false),
    (cid, '6420', 'Ersättningar till revisor', '', true),
    (cid, '6421', 'Revision', '', false),
    (cid, '6422', 'Revisionsverksamhet utöver revision', '', false),
    (cid, '6423', 'Skatterådgivning – revisor', '', false),
    (cid, '6424', 'Övriga tjänster – revisor', '', false),
    (cid, '6430', 'Management fees', '', false),
    (cid, '6440', 'Årsredovisning och delårsrapporter', '', false),
    (cid, '6450', 'Bolagsstämma/års- eller föreningsstämma', '', false),
    (cid, '6490', 'Övriga förvaltningskostnader', '', false),
    (cid, '6500', 'Övriga externa tjänster (gruppkonto)', '', true),
    (cid, '6510', 'Mätningskostnader', '', false),
    (cid, '6520', 'Ritnings- och kopieringskostnader', '', false),
    (cid, '6530', 'Redovisningstjänster', '', false),
    (cid, '6540', 'IT-tjänster', '', false),
    (cid, '6550', 'Konsultarvoden', '', false),
    (cid, '6551', 'Arkitekttjänster', '', false),
    (cid, '6552', 'Teknisk provning och analys', '', false),
    (cid, '6553', 'Tekniska konsulttjänster', '', false),
    (cid, '6554', 'Finansiell- och övrig ekonomisk rådgivning', '', false),
    (cid, '6555', 'Skatterådgivning inkl. insolvens- och konkursförv.', '', false),
    (cid, '6556', 'Köpta tjänster avseende forskning och utveckling', '', false),
    (cid, '6559', 'Övriga konsultarvoden', '', false),
    (cid, '6560', 'Serviceavgifter till branschorganisationer', '', false),
    (cid, '6570', 'Bankkostnader', '', true),
    (cid, '6580', 'Advokat- och rättegångskostnader', '', false),
    (cid, '6590', 'Övriga externa tjänster', '', false),
    (cid, '6700', 'Särskilt för ideella föreningar och stiftelser (gruppkonto)', '', false),
    (cid, '6710', 'Lämnade bidrag', '', false),
    (cid, '6800', 'Inhyrd personal (gruppkonto)', '', true),
    (cid, '6810', 'Inhyrd produktionspersonal', '', true),
    (cid, '6820', 'Inhyrd lagerpersonal', '', true),
    (cid, '6830', 'Inhyrd transportpersonal', '', true),
    (cid, '6840', 'Inhyrd kontors- och ekonomipersonal', '', true),
    (cid, '6850', 'Inhyrd IT-personal', '', true),
    (cid, '6860', 'Inhyrd marknads- och försäljningspersonal', '', true),
    (cid, '6870', 'Inhyrd restaurang- och butikspersonal', '', true),
    (cid, '6880', 'Inhyrda företagsledare', '', true),
    (cid, '6890', 'Övrig inhyrd personal', '', true),
    (cid, '6900', 'Övriga externa kostnader (gruppkonto)', '', true),
    (cid, '6910', 'Licensavgifter och royalties', '', false),
    (cid, '6920', 'Kostnader för egna patent', '', false),
    (cid, '6930', 'Kostnader för varumärken m.m.', '', false),
    (cid, '6940', 'Kontroll-, provnings- och stämpelavgifter', '', false),
    (cid, '6950', 'Tillsynsavgifter myndigheter', '', false),
    (cid, '6970', 'Tidningar, facklitteratur, m.m.', '', false),
    (cid, '6980', 'Föreningsavgifter', '', false),
    (cid, '6981', 'Föreningsavgifter, avdragsgilla', '', false),
    (cid, '6982', 'Föreningsavgifter, ej avdragsgilla', '', false),
    (cid, '6990', 'Övriga externa kostnader', '', false),
    (cid, '6991', 'Övriga externa kostnader, avdragsgilla', '', true),
    (cid, '6992', 'Övriga externa kostnader, ej avdragsgilla', '', true),
    (cid, '6993', 'Lämnade bidrag och gåvor', '', false),
    (cid, '6996', 'Betald utländsk inkomstskatt', '', false),
    (cid, '6997', 'Obetald utländsk inkomstskatt', '', false),
    (cid, '6998', 'Utländsk moms', '', false),
    (cid, '6999', 'Ingående moms, blandad verksamhet', '', false),
    (cid, '7000', 'Löner till kollektivanställda (gruppkonto)', '', true),
    (cid, '7010', 'Löner till kollektivanställda', '', false),
    (cid, '7012', 'Vinstandelar till kollektivanställda', '', false),
    (cid, '7013', 'Lön växa-stöd kollektivanställda 10,21 %', '', false),
    (cid, '7014', 'Löner till kollektivanställda 16,36 %', '', false),
    (cid, '7015', 'Löner till kollektivanställda 6,15 %', '', false),
    (cid, '7016', 'Vinstandelar till kollektivanställda 6,15 %', '', false),
    (cid, '7017', 'Avgångsvederlag till kollektivanställda', '', false),
    (cid, '7018', 'Bruttolöneavdrag, kollektivanställda', '', false),
    (cid, '7019', 'Upplupna löner och vinstandelar till kollektivanställda', '', false),
    (cid, '7030', 'Löner till kollektivanställda (utlandsanställda)', '', false),
    (cid, '7031', 'Löner till kollektivanställda (utlandsanställda)', '', false),
    (cid, '7032', 'Vinstandelar till kollektivanställda (utlandsanställda)', '', false),
    (cid, '7033', 'Löner till kollektivanställda under 26 år (utlandsanställda)', '', false),
    (cid, '7034', 'Löner kollektivaansställda 16,36 %', '', false),
    (cid, '7035', 'Löner till kollektivanställda 6,15 %', '', false),
    (cid, '7036', 'Vinstandelar till kollektivanställda 6,15 % (utlandsanställda)', '', false),
    (cid, '7037', 'Avgångsvederlag till kollektivanställda (utlandsanställda)', '', false),
    (cid, '7038', 'Bruttolöneavdrag, kollektivanställda (utlandsanställda)', '', false),
    (cid, '7039', 'Upplupna löner och vinstandelar till kollektivanställda (utlandsanställda)', '', false),
    (cid, '7080', 'Löner till kollektivanställda för ej arbetad tid', '', false),
    (cid, '7081', 'Sjuklöner till kollektivanställda', '', false),
    (cid, '7082', 'Semesterlöner till kollektivanställda', '', false),
    (cid, '7083', 'Föräldraersättning till kollektivanställda', '', false),
    (cid, '7089', 'Övriga löner till kollektivanställda för ej arbetad tid', '', false),
    (cid, '7090', 'Förändring av semesterlöneskuld', '', false),
    (cid, '7200', 'Löner till tjänstemän och företagsledare (gruppkonto)', '', false),
    (cid, '7210', 'Löner till tjänstemän', '', true),
    (cid, '7212', 'Vinstandelar till tjänstemän', '', false),
    (cid, '7213', 'Lön växa-stöd tjänstemän 10,21 %', '', false),
    (cid, '7214', 'Löner till tjänstemän 16,36 %', '', false),
    (cid, '7215', 'Löner till tjänstemän 6,15 %', '', false),
    (cid, '7216', 'Vinstandelar till tjänstemän 6,15 %', '', false),
    (cid, '7217', 'Avgångsvederlag till tjänstemän', '', false),
    (cid, '7218', 'Bruttolöneavdrag, tjänstemän', '', false),
    (cid, '7219', 'Upplupna löner och vinstandelar till tjänstemän', '', false),
    (cid, '7220', 'Löner till företagsledare', '', true),
    (cid, '7222', 'Tantiem till företagsledare', '', false),
    (cid, '7223', 'Löner till företagsledare 25,46 %', '', false),
    (cid, '7224', 'Löner till företagsledare 16,36 %', '', false),
    (cid, '7225', 'Löner till företagsledare 6,15 %', '', false),
    (cid, '7227', 'Avgångsvederlag till företagsledare', '', false),
    (cid, '7228', 'Bruttolöneavdrag, företagsledare', '', false),
    (cid, '7229', 'Upplupna löner och tantiem till företagsledare', '', false),
    (cid, '7230', 'Löner till tjänstemän och ftgsledare (utlandsanställda)', '', false),
    (cid, '7232', 'Vinstandelar till tjänstemän och ftgsledare (utlandsanställda)', '', false),
    (cid, '7233', 'Löner till tjänstemän och ftgsledare under 26 år (utlandsanställda)', '', false),
    (cid, '7234', 'Löner till tjänstemän och ftgsledare (utlandsanställda) (nya pensionssystemet)', '', false),
    (cid, '7235', 'Löner till tjänstemän och ftgsledare (utlandsanställda) (avgiftsbefriade)', '', false),
    (cid, '7236', 'Vinstandelar till tjänstemän och ftgsledare (utlandsanställda) (avgiftsbefriade)', '', false),
    (cid, '7237', 'Avgångsvederlag till tjänstemän och ftgsledare (utlandsanställda)', '', false),
    (cid, '7238', 'Bruttolöneavdrag, tjänstemän och ftgsledare (utlandsanställda)', '', false),
    (cid, '7239', 'Upplupna löner och vinstandelar till tjänstemän och ftgsledare (utlandsanställda)', '', false),
    (cid, '7240', 'Styrelsearvoden', '', false),
    (cid, '7280', 'Löner till tjänstemän och företagsledare för ej arbetad tid', '', false),
    (cid, '7281', 'Sjuklöner till tjänstemän', '', false),
    (cid, '7282', 'Sjuklöner till företagsledare', '', false),
    (cid, '7283', 'Föräldraersättning till tjänstemän', '', false),
    (cid, '7284', 'Föräldraersättning till företagsledare', '', false),
    (cid, '7285', 'Semesterlöner till tjänstemän', '', false),
    (cid, '7286', 'Semesterlöner till företagsledare', '', false),
    (cid, '7288', 'Övriga löner till tjänstemän för ej arbetad tid', '', false),
    (cid, '7289', 'Övriga löner till företagsledare för ej arbetad tid', '', false),
    (cid, '7290', 'Förändring av semesterlöneskuld', '', false),
    (cid, '7291', 'Förändring av semesterlöneskuld till tjänstemän', '', false),
    (cid, '7292', 'Förändring av semesterlöneskuld till företagsledare', '', false),
    (cid, '7300', 'Kostnadsersättningar och förmåner (gruppkonto)', '', true),
    (cid, '7310', 'Kontanta extraersättningar', '', false),
    (cid, '7311', 'Ersättningar för sammanträden m.m.', '', false),
    (cid, '7312', 'Ersättningar för förslagsverksamhet och uppfinningar', '', false),
    (cid, '7313', 'Ersättningar för/bidrag till bostadskostnader', '', false),
    (cid, '7314', 'Ersättningar för/bidrag till måltidskostnader', '', false),
    (cid, '7315', 'Ersättningar för/bidrag till resor till och från arbetsplatsen', '', false),
    (cid, '7316', 'Ersättningar för/bidrag till arbetskläder', '', false),
    (cid, '7317', 'Ersättningar för/bidrag till arbetsmaterial och arbetsverktyg', '', false),
    (cid, '7318', 'Felräkningspengar', '', false),
    (cid, '7319', 'Övriga kontanta extraersättningar', '', false),
    (cid, '7320', 'Traktamenten vid tjänsteresa', '', false),
    (cid, '7321', 'Skattefria traktamenten, Sverige', '', true),
    (cid, '7322', 'Skattepliktiga traktamenten, Sverige', '', true),
    (cid, '7323', 'Skattefria traktamenten, utlandet', '', true),
    (cid, '7324', 'Skattepliktiga traktamenten, utlandet', '', true),
    (cid, '7330', 'Bilersättningar', '', false),
    (cid, '7331', 'Skattefria bilersättningar', '', true),
    (cid, '7332', 'Skattepliktiga bilersättningar', '', true),
    (cid, '7333', 'Ersättning för trängselskatt, skattefri', '', false),
    (cid, '7350', 'Ersättningar för föreskrivna arbetskläder', '', true),
    (cid, '7370', 'Representationsersättningar', '', false),
    (cid, '7380', 'Kostnader för förmåner till anställda', '', true),
    (cid, '7381', 'Kostnader för fri bostad', '', false),
    (cid, '7382', 'Kostnader för fria eller subventionerade måltider', '', false),
    (cid, '7383', 'Kostnader för fria resor till och från arbetsplatsen', '', false),
    (cid, '7384', 'Kostnader för fria eller subventionerade arbetskläder', '', false),
    (cid, '7385', 'Kostnader för fri bil', '', false),
    (cid, '7386', 'Subventionerad ränta', '', false),
    (cid, '7387', 'Kostnader för lånedatorer', '', false),
    (cid, '7388', 'Anställdas ersättning för erhållna förmåner', '', false),
    (cid, '7389', 'Övriga kostnader för förmåner', '', false),
    (cid, '7390', 'Övriga kostnadsersättningar och förmåner', '', true),
    (cid, '7391', 'Kostnad för trängselskatteförmån', '', false),
    (cid, '7392', 'Kostnad för förmån av hushållsnära tjänster', '', false),
    (cid, '7399', 'Motkontering förmåner', '', true),
    (cid, '7400', 'Pensionskostnader (gruppkonto)', '', false),
    (cid, '7410', 'Pensionsförsäkringspremier', '', true),
    (cid, '7411', 'Premier för kollektiva pensionsförsäkringar', '', false),
    (cid, '7412', 'Premier för individuella pensionsförsäkringar', '', false),
    (cid, '7418', 'Återbäring från försäkringsföretag', '', false),
    (cid, '7420', 'Förändring av pensionsskuld', '', false),
    (cid, '7430', 'Avdrag för räntedel i pensionskostnad', '', false),
    (cid, '7440', 'Förändring av pensionsstiftelsekapital', '', false),
    (cid, '7441', 'Överföring av medel till pensionsstiftelse', '', false),
    (cid, '7448', 'Gottgörelse från pensionsstiftelse', '', false),
    (cid, '7460', 'Pensionsutbetalningar', '', false),
    (cid, '7461', 'Pensionsutbetalningar till f.d. kollektivanställda', '', false),
    (cid, '7462', 'Pensionsutbetalningar till f.d. tjänstemän', '', false),
    (cid, '7463', 'Pensionsutbetalningar till f.d. företagsledare', '', false),
    (cid, '7470', 'Förvaltnings- och kreditförsäkringsavgifter', '', false),
    (cid, '7490', 'Övriga pensionskostnader', '', false),
    (cid, '7500', 'Sociala och andra avgifter enligt lag och avtal (gruppkonto)', '', true),
    (cid, '7510', 'Arbetsgivaravgifter 31,42 %', '', true),
    (cid, '7511', 'Arbetsgivaravgifter för löner och ersättningar', '', false),
    (cid, '7512', 'Arbetsgivaravgifter för förmånsvärden', '', false),
    (cid, '7513', 'Arbetsgivaravgift avdrag forskning', '', true),
    (cid, '7514', 'Arbetsgivaravgift första anställd', '', true),
    (cid, '7515', 'Arbetsgivaravgifter på skattepliktiga kostnadsersättningar', '', false),
    (cid, '7516', 'Arbetsgivaravgifter på arvoden', '', false),
    (cid, '7518', 'Arbetsgivaravgifter på bruttolöneavdrag m.m.', '', false),
    (cid, '7519', 'Arbetsgivaravgifter för semester- och löneskulder', '', false),
    (cid, '7520', 'Avgifter 16,36 %', '', false),
    (cid, '7521', 'Avgifter för löner och ersättningar', '', false),
    (cid, '7522', 'Avgifter för förmånsvärden', '', false),
    (cid, '7525', 'Avgifter på skattepliktiga kostnadsersättningar', '', false),
    (cid, '7526', 'Avgifter på arvoden', '', false),
    (cid, '7528', 'Avgifter på bruttolöneavdrag m.m.', '', false),
    (cid, '7529', 'Avgifter för semester- och löneskulder', '', false),
    (cid, '7530', 'Särskild löneskatt', '', false),
    (cid, '7531', 'Särskild löneskatt för vissa försäkringsersättningar m.m.', '', false),
    (cid, '7532', 'Särskild löneskatt pensionskostnader, deklarationspost', '', false),
    (cid, '7533', 'Särskild löneskatt för pensionskostnader', '', true),
    (cid, '7534', 'Särskild löneskatt förvärvsinkomster 6,15 %', '', false),
    (cid, '7550', 'Avkastningsskatt på pensionsmedel', '', false),
    (cid, '7551', 'Avkastningsskatt 15% försäkringsföretag m.fl. samt avsatt till pensioner', '', false),
    (cid, '7552', 'Avkastningsskatt 15% utländska pensionsförsäkringar', '', false),
    (cid, '7553', 'Avkastningsskatt 30 % utländska försäkringsföretag m.fl.', '', false),
    (cid, '7554', 'Avkastningsskatt 30% utländska kapitalförsäkringar', '', false),
    (cid, '7560', 'Arbetsgivaravgifter 25,46 %', '', true),
    (cid, '7570', 'Premier för arbetsmarknadsförsäkringar', '', false),
    (cid, '7571', 'Arbetsmarknadsförsäkringar', '', false),
    (cid, '7572', 'Arbetsmarknadsförsäkringar pensionsförsäkringspremier, deklarationspost', '', false),
    (cid, '7573', 'Arbetsmarknadsförsäkringar, betalda premier och avgifter', '', false),
    (cid, '7580', 'Gruppförsäkringspremier', '', false),
    (cid, '7581', 'Grupplivförsäkringspremier', '', false),
    (cid, '7582', 'Gruppsjukförsäkringspremier', '', false),
    (cid, '7583', 'Gruppolycksfallsförsäkringspremier', '', false),
    (cid, '7589', 'Övriga gruppförsäkringspremier', '', false),
    (cid, '7590', 'Övriga sociala och andra avgifter enligt lag och avtal', '', false),
    (cid, '7600', 'Övriga personalkostnader (gruppkonto)', '', true),
    (cid, '7610', 'Utbildning', '', false),
    (cid, '7620', 'Sjuk- och hälsovård', '', false),
    (cid, '7621', 'Sjuk- och hälsovård, avdragsgill', '', false),
    (cid, '7622', 'Sjuk- och hälsovård, ej avdragsgill', '', false),
    (cid, '7623', 'Sjukvårdsförsäkring, ej avdragsgill', '', false),
    (cid, '7630', 'Personalrepresentation', '', false),
    (cid, '7631', 'Personalrepresentation, avdragsgill', '', false),
    (cid, '7632', 'Personalrepresentation, ej avdragsgill', '', false),
    (cid, '7650', 'Sjuklöneförsäkring', '', false),
    (cid, '7670', 'Förändring av personalstiftelsekapital', '', false),
    (cid, '7671', 'Avsättning till personalstiftelse', '', false),
    (cid, '7678', 'Gottgörelse från personalstiftelse', '', false),
    (cid, '7690', 'Övriga personalkostnader', '', false),
    (cid, '7691', 'Personalrekrytering', '', false),
    (cid, '7692', 'Begravningshjälp', '', false),
    (cid, '7693', 'Fritidsverksamhet', '', false),
    (cid, '7699', 'Övriga personalkostnader', '', false),
    (cid, '7710', 'Nedskrivningar av immateriella anläggningstillgångar', '', false),
    (cid, '7720', 'Nedskrivningar av byggnader och mark', '', false),
    (cid, '7730', 'Nedskrivningar av maskiner respektive inventarier', '', false),
    (cid, '7731', 'Nedskrivningar av maskiner och andra tekniska anläggningar', '', true),
    (cid, '7732', 'Nedskrivningar av inventarier, verktyg och installationer', '', true),
    (cid, '7733', 'Nedskrivningar av övriga materiella anläggningstillgångar', '', true),
    (cid, '7740', 'Nedskrivningar av vissa omsättningstillgångar', '', false),
    (cid, '7760', 'Återföring av nedskrivningar av immateriella anläggningstillgångar', '', false),
    (cid, '7770', 'Återföring av nedskrivningar av byggnader och mark', '', false),
    (cid, '7780', 'Återföring av nedskrivningar av maskiner respektive inventarier', '', false),
    (cid, '7781', 'Återföring av nedskrivningar av maskiner och andra tekniska anläggningar', '', true),
    (cid, '7782', 'Återföring av nedskrivningar av inventarier, verktyg och installationer', '', true),
    (cid, '7783', 'Återföring av nedskrivningar av övriga materiella anläggningstillgångar', '', true),
    (cid, '7790', 'Återföring av nedskrivningar av vissa omsättningstillgångar', '', false),
    (cid, '7810', 'Avskrivningar på immateriella anläggningstillgångar', '', false),
    (cid, '7811', 'Avskrivningar på balanserade utgifter', '', false),
    (cid, '7812', 'Avskrivningar på koncessioner m.m.', '', false),
    (cid, '7813', 'Avskrivningar på patent', '', false),
    (cid, '7814', 'Avskrivningar på licenser', '', false),
    (cid, '7815', 'Avskrivningar på varumärken', '', false),
    (cid, '7816', 'Avskrivningar på hyresrätter', '', false),
    (cid, '7817', 'Avskrivningar på goodwill', '', false),
    (cid, '7819', 'Avskrivningar på övriga immateriella anläggningstillgångar', '', false),
    (cid, '7820', 'Avskrivningar på byggnader och markanläggningar', '', false),
    (cid, '7821', 'Avskrivningar på byggnader', '', false),
    (cid, '7824', 'Avskrivningar på markanläggningar', '', false),
    (cid, '7829', 'Avskrivningar på övriga byggnader', '', false),
    (cid, '7830', 'Avskrivningar på maskiner respektive inventarier', '', false),
    (cid, '7831', 'Avskrivningar på maskiner och andra tekniska anläggningar', '', true),
    (cid, '7832', 'Avskrivningar på inventarier, verktyg och installationer', '', true),
    (cid, '7834', 'Avskrivningar på bilar och andra transportmedel', '', false),
    (cid, '7835', 'Avskrivningar på datorer', '', false),
    (cid, '7836', 'Avskrivningar på leasade tillgångar', '', false),
    (cid, '7839', 'Avskrivningar på övriga materiella anläggningstillgångar', '', false),
    (cid, '7840', 'Avskrivningar på förbättringsutgifter på annans fastighet', '', false),
    (cid, '7940', 'Orealiserade positiva/negativa värdeförändringar på säkringsinstrument', '', false),
    (cid, '7960', 'Valutakursförluster på fordringar och skulder av rörelsekaraktär', '', true),
    (cid, '7970', 'Förlust vid avyttring av immateriella och materiella anläggningstillgångar', '', false),
    (cid, '7971', 'Förlust vid avyttring av immateriella anläggningstillgångar', '', false),
    (cid, '7972', 'Förlust vid avyttring av byggnader och mark', '', false),
    (cid, '7973', 'Förlust vid avyttring av maskiner och inventarier', '', true),
    (cid, '7990', 'Övriga rörelsekostnader', '', false),
    (cid, '8010', 'Utdelning på andelar i koncernföretag', '', false),
    (cid, '8012', 'Utdelning på andelar i dotterföretag', '', false),
    (cid, '8016', 'Emissionsinsats, koncernföretag', '', false),
    (cid, '8020', 'Resultat vid försäljning av andelar i koncernföretag', '', false),
    (cid, '8030', 'Resultatandelar från handelsbolag (dotterföretag)', '', false),
    (cid, '8070', 'Nedskrivningar av andelar i och långfristiga fordringar hos koncernföretag', '', false),
    (cid, '8072', 'Nedskrivningar av andelar i dotterföretag', '', false),
    (cid, '8076', 'Nedskrivningar av långfristiga fordringar hos moderföretag', '', false),
    (cid, '8077', 'Nedskrivningar av långfristiga fordringar hos dotterföretag', '', false),
    (cid, '8080', 'Återföringar av nedskrivningar av andelar i och långfristiga fordringar hos koncernföretag', '', false),
    (cid, '8082', 'Återföringar av nedskrivningar av andelar i dotterföretag', '', false),
    (cid, '8086', 'Återföringar av nedskrivningar av långfristiga fordringar hos moderföretag', '', false),
    (cid, '8087', 'Återföringar av nedskrivningar av långfristiga fordringar hos dotterföretag', '', false),
    (cid, '8110', 'Utdelningar på andelar i intresseftg, gemensamt styrda ftg, övriga ägarintr ftg', '', false),
    (cid, '8111', 'Utdelningar på andelar i intresseföretag', '', false),
    (cid, '8112', 'Utdelningar på andelar i gemensamt styrda företag', '', false),
    (cid, '8113', 'Utdelningar på andelar i övriga företag som det finns ett ägarintresse i', '', false),
    (cid, '8116', 'Emissionsinsats, intresseföretag', '', false),
    (cid, '8117', 'Emissionsinsats, gemensamt styrda företag', '', false),
    (cid, '8118', 'Emissionsinsats, övriga företag som det finns ett ägarintresse i', '', false),
    (cid, '8120', 'Resultat vid försäljning av andelar i intresseftg, gemensamt styrda ftg, övriga ägarintr ftg', '', false),
    (cid, '8121', 'Resultat vid försäljning av andelar i intresseföretag', '', false),
    (cid, '8122', 'Resultat vid försäljning av andelar i gemensamt styrda företag', '', false),
    (cid, '8123', 'Resultat vid försäljning av andelar i övriga företag som det finns ett ägarintresse i', '', false),
    (cid, '8130', 'Resultatandelar från handelsbolag (intresseftg, gemensamt styrda ftg, övriga ägarintr ftg)', '', false),
    (cid, '8131', 'Resultatandelar från handelsbolag (intresseföretag)', '', false),
    (cid, '8132', 'Resultatandelar från handelsbolag (gemensamt styrda företag)', '', false),
    (cid, '8133', 'Resultatandelar från handelsbolag (övriga företag som det finns ett ägarintresse i)', '', false),
    (cid, '8170', 'Nedskr av andelar i och långfr fordringar hos intresseftg, gemensamt styrda ftg, övriga ägarintr ftg', '', false),
    (cid, '8171', 'Nedskrivningar av andelar i intresseföretag', '', false),
    (cid, '8172', 'Nedskrivningar av långfristiga fordringar hos intresseföretag', '', false),
    (cid, '8173', 'Nedskrivningar av andelar i gemensamt styrda företag', '', false),
    (cid, '8174', 'Nedskrivningar av långfristiga fordringar hos gemensamt styrda företag', '', false),
    (cid, '8176', 'Nedskrivningar av andelar i övriga företag som det finns ett ägarintresse i', '', false),
    (cid, '8177', 'Nedskrivningar av långfristiga fordringar hos övriga företag som det finns ett ägarintresse i', '', false),
    (cid, '8180', 'Återf av nedskr av andelar i och långfr fordr hos intresseftg, gemensamt styrda, övriga ägarintr ftg', '', false),
    (cid, '8181', 'Återföringar av nedskrivningar av andelar i intresseföretag', '', false),
    (cid, '8182', 'Återföringar av nedskrivningar av långfristiga fordringar hos intresseföretag', '', false),
    (cid, '8183', 'Återföringar av nedskrivningar av andelar i gemensamt styrda företag', '', false),
    (cid, '8184', 'Återföringar av nedskrivningar av långfristiga fordringar hos gemensamt styrda företag', '', false),
    (cid, '8186', 'Återföringar av nedskrivningar av andelar i övriga företag som det finns ett ägarintresse i', '', false),
    (cid, '8187', 'Andelar i intresseföretag, gemensamt styrda företag och övriga företag som finns ett ägarintresse i', '', false),
    (cid, '8210', 'Utdelningar på andelar i andra företag', '', false),
    (cid, '8212', 'Utdelningar, andra företag', '', false),
    (cid, '8216', 'Insatsemissioner, andra företag', '', false),
    (cid, '8220', 'Resultat vid försäljning av värdepapper i och långfristiga fordringar hos andra företag', '', false),
    (cid, '8221', 'Resultat vid försäljning av andelar i andra företag', '', false),
    (cid, '8222', 'Resultat vid försäljning av långfristiga fordringar hos andra företag', '', false),
    (cid, '8223', 'Resultat vid försäljning av derivat (långfristiga värdepappersinnehav)', '', false),
    (cid, '8230', 'Valutakursdifferenser på långfristiga fordringar', '', false),
    (cid, '8231', 'Valutakursvinster på långfristiga fordringar', '', false),
    (cid, '8236', 'Valutakursförluster på långfristiga fordringar', '', false),
    (cid, '8240', 'Resultatandelar från handelsbolag (andra företag)', '', false),
    (cid, '8250', 'Ränteintäkter från långfristiga fordringar hos och värdepapper i andra företag', '', false),
    (cid, '8251', 'Ränteintäkter från långfristiga fordringar', '', false),
    (cid, '8252', 'Ränteintäkter från övriga värdepapper', '', false),
    (cid, '8254', 'Skattefria ränteintäkter, långfristiga tillgångar', '', false),
    (cid, '8255', 'Avkastningsskatt kapitalplacering', '', false),
    (cid, '8260', 'Ränteintäkter från långfristiga fordringar hos koncernföretag', '', false),
    (cid, '8261', 'Ränteintäkter från långfristiga fordringar hos moderföretag', '', false),
    (cid, '8262', 'Ränteintäkter från långfristiga fordringar hos dotterföretag', '', false),
    (cid, '8263', 'Ränteintäkter från långfristiga fordringar hos andra koncernföretag', '', false),
    (cid, '8270', 'Nedskrivningar av innehav av andelar i och långfristiga fordringar hos andra företag', '', false),
    (cid, '8271', 'Nedskrivningar av andelar i andra företag', '', false),
    (cid, '8272', 'Nedskrivningar av långfristiga fordringar hos andra företag', '', false),
    (cid, '8273', 'Nedskrivningar av övriga värdepapper hos andra företag', '', false),
    (cid, '8280', 'Återföringar av nedskrivningar av andelar i och långfristiga fordringar hos andra företag', '', false),
    (cid, '8281', 'Återföringar av nedskrivningar av andelar i andra företag', '', false),
    (cid, '8282', 'Återföringar av nedskrivningar av långfristiga fordringar hos andra företag', '', false),
    (cid, '8283', 'Återföringar av nedskrivningar av övriga värdepapper i andra företag', '', false),
    (cid, '8290', 'Värdering till verkligt värde, anläggningstillgångar', '', false),
    (cid, '8291', 'Orealiserade värdeförändringar på anläggningstillgångar', '', false),
    (cid, '8295', 'Orealiserade värdeförändringar på derivatinstrument', '', false),
    (cid, '8310', 'Ränteintäkter från omsättningstillgångar', '', false),
    (cid, '8311', 'Ränteintäkter från bank', '', false),
    (cid, '8312', 'Ränteintäkter från kortfristiga placeringar', '', false),
    (cid, '8313', 'Ränteintäkter från kortfristiga fordringar', '', false),
    (cid, '8314', 'Skattefria ränteintäkter', '', true),
    (cid, '8317', 'Ränteintäkter för dold räntekompensation', '', false),
    (cid, '8319', 'Övriga ränteintäkter från omsättningstillgångar', '', false),
    (cid, '8320', 'Värdering till verkligt värde, omsättningstillgångar', '', false),
    (cid, '8321', 'Orealiserade värdeförändringar på omsättningstillgångar', '', false),
    (cid, '8325', 'Orealiserade värdeförändringar på derivatinstrument (oms.-tillg.)', '', false),
    (cid, '8330', 'Valutakursdifferenser på kortfristiga fordringar och placeringar', '', true),
    (cid, '8331', 'Valutakursvinster på kortfristiga fordringar och placeringar', '', false),
    (cid, '8336', 'Valutakursförluster på kortfristiga fordringar och placeringar', '', false),
    (cid, '8340', 'Utdelningar på kortfristiga placeringar', '', false),
    (cid, '8350', 'Resultat vid försäljning av kortfristiga placeringar', '', false),
    (cid, '8360', 'Övriga ränteintäkter från koncernföretag', '', false),
    (cid, '8361', 'Övriga ränteintäkter från moderföretag', '', false),
    (cid, '8362', 'Övriga ränteintäkter från dotterföretag', '', false),
    (cid, '8363', 'Övriga ränteintäkter från andra koncernföretag', '', false),
    (cid, '8370', 'Nedskrivningar av kortfristiga placeringar', '', false),
    (cid, '8380', 'Återföringar av nedskrivningar av kortfristiga placeringar', '', false),
    (cid, '8390', 'Övriga finansiella intäkter', '', false),
    (cid, '8400', 'Räntekostnader (gruppkonto)', '', true),
    (cid, '8410', 'Räntekostnader för långfristiga skulder', '', false),
    (cid, '8411', 'Räntekostnader för obligations-, förlags- och konvertibla lån', '', false),
    (cid, '8412', 'Räntedel i årets pensionskostnad', '', false),
    (cid, '8413', 'Räntekostnader för kontokredit', '', false),
    (cid, '8415', 'Räntekostnader för andra skulder till kreditinstitut', '', false),
    (cid, '8417', 'Räntekostnader för dold räntekompensation m.m.', '', false),
    (cid, '8418', 'Avdragspost för räntesubventioner', '', false),
    (cid, '8419', 'Övriga räntekostnader för långfristiga skulder', '', false),
    (cid, '8420', 'Räntekostnader för kortfristiga skulder', '', false),
    (cid, '8421', 'Räntekostnader till kreditinstitut', '', false),
    (cid, '8422', 'Dröjsmålsräntor för leverantörsskulder', '', true),
    (cid, '8423', 'Räntekostnader för skatter och avgifter', '', true),
    (cid, '8424', 'Räntekostnader byggnadskreditiv', '', false),
    (cid, '8429', 'Övriga räntekostnader för kortfristiga skulder', '', false),
    (cid, '8430', 'Valutakursdifferenser på skulder', '', true),
    (cid, '8431', 'Valutakursvinster på skulder', '', false),
    (cid, '8436', 'Valutakursförluster på skulder', '', false),
    (cid, '8440', 'Erhållna räntebidrag', '', false),
    (cid, '8450', 'Orealiserade värdeförändringar på skulder', '', false),
    (cid, '8451', 'Orealiserade värdeförändringar på skulder', '', false),
    (cid, '8455', 'Orealiserade värdeförändringar på säkringsinstrument', '', false),
    (cid, '8460', 'Räntekostnader till koncernföretag', '', false),
    (cid, '8461', 'Räntekostnader till moderföretag', '', false),
    (cid, '8462', 'Räntekostnader till dotterföretag', '', false),
    (cid, '8463', 'Räntekostnader till andra koncernföretag', '', false),
    (cid, '8480', 'Aktiverade ränteutgifter', '', false),
    (cid, '8490', 'Övriga skuldrelaterade poster', '', false),
    (cid, '8491', 'Erhållet ackord på skulder till kreditinstitut m.m.', '', false),
    (cid, '8810', 'Förändring av periodiseringsfond', '', false),
    (cid, '8811', 'Avsättning till periodiseringsfond', '', true),
    (cid, '8819', 'Återföring från periodiseringsfond', '', true),
    (cid, '8820', 'Mottagna koncernbidrag', '', false),
    (cid, '8830', 'Lämnade koncernbidrag', '', false),
    (cid, '8840', 'Lämnade gottgörelser', '', false),
    (cid, '8850', 'Förändring av överavskrivningar', '', true),
    (cid, '8851', 'Förändring av överavskrivningar, immateriella anläggningstillgångar', '', false),
    (cid, '8852', 'Förändring av överavskrivningar, byggnader och markanläggningar', '', false),
    (cid, '8853', 'Förändring av överavskrivningar, maskiner respektive inventarier', '', false),
    (cid, '8860', 'Förändring av ersättningsfond', '', false),
    (cid, '8861', 'Avsättning till ersättningsfond för inventarier', '', false),
    (cid, '8862', 'Avsättning till ersättningsfond för byggnader och markanläggningar', '', false),
    (cid, '8864', 'Avsättning till ersättningsfond för djurlager i jordbruk och renskötsel', '', false),
    (cid, '8865', 'Ianspråktagande av ersättningsfond för avskrivningar', '', false),
    (cid, '8866', 'Ianspråktagande av ersättningsfond för annat än avskrivningar', '', false),
    (cid, '8869', 'Återföring från ersättningsfond', '', false),
    (cid, '8880', 'Förändring av obeskattade intäkter', '', false),
    (cid, '8881', 'Avsättning till upphovsmannakonto', '', false),
    (cid, '8882', 'Återföring från upphovsmannakonto', '', false),
    (cid, '8885', 'Avsättning till skogskonto', '', false),
    (cid, '8886', 'Återföring från skogskonto', '', false),
    (cid, '8890', 'Övriga bokslutsdispositioner', '', false),
    (cid, '8892', 'Nedskrivningar av konsolideringskaraktär av anläggningstillgångar', '', false),
    (cid, '8896', 'Förändring av lagerreserv', '', false),
    (cid, '8899', 'Övriga bokslutsdispositioner', '', false),
    (cid, '8910', 'Skatt som belastar årets resultat', '', true),
    (cid, '8920', 'Skatt på grund av ändrad beskattning', '', false),
    (cid, '8930', 'Restituerad skatt', '', false),
    (cid, '8940', 'Uppskjuten skatt', '', false),
    (cid, '8980', 'Övriga skatter', '', false),
    (cid, '8990', 'Resultat', '', false),
    (cid, '8999', 'Årets resultat', '', true);
END $$;
