// BokPilots handbok – artiklar. Utbyggbart: lägg till fler objekt i listan utan att röra UI.
// Varje artikel följer den gemensamma strukturen (titel, sammanfattning, syfte, när, steg,
// viktiga fält, vanliga fel + så rättar du, exempel, relaterade, senast uppdaterad, version).
const V = 'BokPilot 1.0'
const D = '2026-06-22'

// Kompakt byggare: a({ id, slug, title, category, keywords, related, role, ...sektioner })
const a = (o) => ({
  id: o.id, slug: o.slug, title: o.title, category: o.category,
  keywords: o.keywords || [], relatedArticles: o.related || [],
  requiredRole: o.role || 'user', updatedAt: o.updatedAt || D, appVersion: V, source: 'internal',
  summary: o.summary || '', purpose: o.purpose || '', when: o.when || '',
  steps: o.steps || [], fields: o.fields || [], errors: o.errors || [], example: o.example || '',
})

export const HELP_ARTICLES = [
  // ─────────────────────────── Kom igång ───────────────────────────
  a({ id: 'help-login', slug: 'logga-in', title: 'Logga in i BokPilot', category: 'Kom igång',
    keywords: ['logga in', 'inloggning', 'lösenord', 'konto'], related: ['valj-foretag', 'forsta-sidomenyn'],
    summary: 'Så loggar du in och kommer åt ditt företags bokföring.',
    purpose: 'Inloggningen ger dig säker åtkomst till företagets data. Varje användare har ett eget konto.',
    when: 'Första gången du börjar arbeta, eller när du loggats ut.',
    steps: ['Gå till app.bokpilot.se.', 'Ange din e-postadress och ditt lösenord.', 'Klicka på Logga in.', 'Saknar du konto – be en administratör bjuda in dig under Inställningar → Team.'],
    fields: [['E-post', 'Adressen du blev inbjuden med.'], ['Lösenord', 'Ditt personliga lösenord.']],
    errors: [['"Sessionen har gått ut"', 'Logga in igen – din inloggning förnyas automatiskt men kan löpa ut efter inaktivitet.'], ['Fel lösenord', 'Använd "Glömt lösenord" för att återställa.']],
    example: 'info@acountx.se loggar in och möts av Dashboard för senast valda företag.' }),

  a({ id: 'help-select-company', slug: 'valj-foretag', title: 'Välj företag', category: 'Kom igång',
    keywords: ['företag', 'byt företag', 'flera bolag'], related: ['logga-in', 'foretagsinstallningar'],
    summary: 'Hantera flera bolag och byt mellan dem.',
    purpose: 'BokPilot stöder flera företag per användare. Allt du gör sker i det valda företaget.',
    when: 'När du sköter bokföring för mer än ett bolag.',
    steps: ['Klicka på företagsnamnet nere till vänster i sidomenyn.', 'Välj företag i listan, eller "Skapa nytt företag".', 'Vid nytt företag: ange organisationsnummer – namnet hämtas automatiskt.'],
    fields: [['Organisationsnummer', 'Används för att hämta företagsnamn och som identitet.']],
    errors: [['Ser fel företags data', 'Kontrollera vilket företag som är valt nere till vänster och byt.']],
    example: 'Du växlar från "BokPilot AB" till ett klientbolag innan du bokför deras kvitton.' }),

  a({ id: 'help-sidebar', slug: 'forsta-sidomenyn', title: 'Förstå sidomenyn', category: 'Kom igång',
    keywords: ['meny', 'navigering', 'sidomeny'], related: ['valj-foretag', 'grundinstallningar'],
    summary: 'Översikt över sidomenyns sektioner och hur du navigerar.',
    purpose: 'Sidomenyn är navet: Översikt, Ekonomi, Register, Hjälp och Inställningar.',
    when: 'När du letar efter en funktion.',
    steps: ['Översikt: Dashboard, AI-assistent, AI-ekonomichef.', 'Ekonomi: Inkorg, Bokföring, fakturor, Kassa och bank, Kontoanalys, Lön, Moms, Rapporter, AI-granskning.', 'Register: Kunder, Leverantörer, Produkter.', 'Fäll ihop menyn med pilen uppe till höger i menyn för mer arbetsyta.'],
    fields: [['Huvudval med flikar', 'Vissa val (t.ex. Lön) öppnar toppflikar i innehållsytan i stället för undermeny.']],
    errors: [['Hittar inte en funktion', 'Använd handbokens sökruta eller AI-hjälpen.']],
    example: 'Lön → öppnar flikarna Löner och Anställda högst upp i innehållsytan.' }),

  a({ id: 'help-basic-settings', slug: 'grundinstallningar', title: 'Grundinställningar', category: 'Kom igång',
    keywords: ['inställningar', 'räkenskapsår', 'kontoplan', 'komma igång'], related: ['foretagsinstallningar', 'kontoplan'],
    summary: 'Det du bör ställa in innan du börjar bokföra.',
    purpose: 'Korrekta grunduppgifter ger rätt bokföring från start.',
    when: 'Direkt efter att företaget skapats.',
    steps: ['Kontrollera företagsuppgifter under Inställningar.', 'Säkerställ att rätt räkenskapsår är upplagt.', 'Gå igenom kontoplanen (BAS).', 'Lägg upp kassa-/bankkonton och e-postadress för underlag.'],
    fields: [['Räkenskapsår', 'Styr vilka perioder du kan bokföra i.'], ['Kontoplan', 'BAS-konton som används vid kontering.']],
    errors: [['Kan inte bokföra på ett datum', 'Datumet ligger utanför upplagt räkenskapsår – lägg upp året först.']],
    example: 'Nytt bolag: lägg upp räkenskapsår 2026 innan första verifikationen.' }),

  a({ id: 'help-first-customer', slug: 'lagg-till-forsta-kunden', title: 'Lägg till första kunden', category: 'Kom igång',
    keywords: ['kund', 'register', 'kundfaktura'], related: ['skapa-kundfaktura', 'lagg-till-forsta-leverantoren'],
    summary: 'Lägg upp en kund för att kunna fakturera.',
    purpose: 'Kundregistret återanvänds på kundfakturor.',
    when: 'Innan du skapar din första kundfaktura.',
    steps: ['Gå till Register → Kunder.', 'Klicka Ny kund.', 'Fyll i namn och ev. org.nr, adress och e-post.', 'Spara.'],
    fields: [['Namn', 'Obligatoriskt.'], ['Org.nr', 'Behövs för företagskunder och e-faktura.']],
    errors: [['Dubbletter', 'Sök innan du lägger till – kunden kan redan finnas.']],
    example: 'Lägg upp "Exempel Kund AB" och fakturera direkt.' }),

  a({ id: 'help-first-supplier', slug: 'lagg-till-forsta-leverantoren', title: 'Lägg till första leverantören', category: 'Kom igång',
    keywords: ['leverantör', 'register'], related: ['skapa-leverantorsfaktura', 'lagg-till-forsta-kunden'],
    summary: 'Lägg upp en leverantör för leverantörsfakturor.',
    purpose: 'Leverantörsregistret kopplas till leverantörsfakturor och inlärda konteringsregler.',
    when: 'Innan du registrerar leverantörsfakturor.',
    steps: ['Gå till Register → Leverantörer.', 'Klicka Ny leverantör.', 'Fyll i namn, org.nr och betaluppgifter (bankgiro/plusgiro).', 'Spara.'],
    fields: [['Bankgiro/Plusgiro', 'Används vid betalning.'], ['Standardmotkonto', 'Föreslås vid kontering (kan läras in automatiskt).']],
    errors: [['Fel betaluppgift', 'Kontrollera bankgiro innan betalning skapas.']],
    example: 'Lägg upp "Grenkeleasing AB" så känns återkommande fakturor igen.' }),

  // ─────────────────────────── Dashboard ───────────────────────────
  a({ id: 'help-dashboard', slug: 'dashboard-oversikt', title: 'Dashboard – översikt', category: 'Dashboard',
    keywords: ['dashboard', 'översikt', 'nyckeltal'], related: ['rapport-resultat', 'kontoanalys-oversikt'],
    summary: 'Startvyn med status och nyckeltal för företaget.',
    purpose: 'Ger en snabb bild av läget: att göra, senaste händelser och nyckeltal.',
    when: 'När du loggar in och vill se vad som behöver åtgärdas.',
    steps: ['Öppna Dashboard i Översikt.', 'Klicka på en widget för att gå till detaljvyn.'],
    fields: [],
    errors: [['Tomt på Dashboard', 'Nytt företag har ännu ingen data – börja med Inkorg eller Bokföring.']],
    example: 'Dashboard visar antal underlag som väntar på granskning.' }),

  // ─────────────────────────── AI-assistent ───────────────────────────
  a({ id: 'help-ai-assistant', slug: 'ai-assistent', title: 'AI-assistenten', category: 'AI-assistent',
    keywords: ['ai', 'assistent', 'fråga', 'hjälp'], related: ['ai-tolkning-fungerar', 'ai-granskning-oversikt'],
    summary: 'Ställ frågor om bokföring och få källbundna svar.',
    purpose: 'AI-assistenten hjälper dig att bokföra och svarar på bokföringsfrågor utifrån BokPilots regelverk.',
    when: 'När du är osäker på hur ett underlag ska bokföras.',
    steps: ['Öppna AI-assistenten i Översikt, eller den glödande AI-knappen i bokföringsvyerna.', 'Skriv din fråga eller tolka ett kopplat underlag.', 'Granska förslaget och källorna innan du tillämpar det.'],
    fields: [['Källor', 'Varje svar visar vilka regelverk/sidor det bygger på.'], ['Konfidens', 'Lägre konfidens flaggar för manuell granskning.']],
    errors: [['"Det framgår inte av källorna"', 'Frågan ligger utanför regelverket – kontrollera manuellt eller kontakta redovisningskonsult.']],
    example: 'Fråga: "Hur bokför jag ett kvitto med 12 % moms?" → förslag med konton + källa.' }),

  // ─────────────────────────── Inkorg ───────────────────────────
  a({ id: 'help-inbox-upload', slug: 'ladda-upp-underlag', title: 'Ladda upp underlag', category: 'Inkorg',
    keywords: ['inkorg', 'underlag', 'ladda upp', 'pdf', 'kvitto', 'faktura'], related: ['dra-och-slapp-filer', 'tolka-underlag-med-ai', 'epost-for-underlag'],
    summary: 'Lägg in kvitton och fakturor digitalt i Inkorgen.',
    purpose: 'Inkorgen samlar alla underlag innan de bokförs. Sparas digitalt och arkiverat.',
    when: 'När du fått ett kvitto eller en faktura.',
    steps: ['Gå till Inkorg.', 'Klicka Ladda upp och välj fil (PDF, JPG, PNG, WEBP).', 'Underlaget klassas automatiskt och hamnar i rätt kategori.'],
    fields: [['Filtyp', 'PDF, JPG/JPEG, PNG, WEBP. Inte exe/zip/html.'], ['Kategori', 'Sätts automatiskt (kvitto, leverantörsfaktura, dagskassa m.m.).']],
    errors: [['"Ej tillåten filtyp"', 'Spara om underlaget som PDF eller bild.'], ['För stor fil', 'Max 25 MB – komprimera eller dela upp.']],
    example: 'Ladda upp "kvitto.pdf" → klassas som kvitto, redo att kopplas/tolkas.' }),

  a({ id: 'help-drag-drop', slug: 'dra-och-slapp-filer', title: 'Dra och släpp filer', category: 'Inkorg',
    keywords: ['dra och släpp', 'drag', 'ladda upp'], related: ['ladda-upp-underlag', 'koppla-bild-till-faktura'],
    summary: 'Dra filer direkt in i underlagspanelen.',
    purpose: 'Snabbaste sättet att lägga in flera underlag.',
    when: 'När du har filer på datorn att lägga in.',
    steps: ['Öppna Inkorgen eller dokumentpanelen (Koppla bild).', 'Dra en eller flera filer från datorn till ytan.', 'Släpp – filerna laddas upp och visas i listan.'],
    fields: [],
    errors: [['Inget händer vid släpp', 'Kontrollera att du släpper i uppladdningsytan och att filtypen stöds.']],
    example: 'Dra tre kvitton samtidigt till panelen – alla laddas upp.' }),

  a({ id: 'help-couple-image', slug: 'koppla-bild-till-faktura', title: 'Koppla bild till faktura', category: 'Inkorg',
    keywords: ['koppla', 'bild', 'underlag', 'verifikation'], related: ['ladda-upp-underlag', 'skapa-verifikation', 'skapa-leverantorsfaktura'],
    summary: 'Knyt ett underlag till en verifikation eller faktura.',
    purpose: 'Spårbarhet (BFL): varje bokförd post ska ha sitt underlag kopplat.',
    when: 'När du bokför ett underlag eller kompletterar en post i efterhand.',
    steps: ['Öppna dokumentpanelen (Koppla bild/Välj underlag).', 'Bläddra i inkorgen eller välj i rullistan över uppladdade underlag.', 'Klicka Koppla.'],
    fields: [['Rullista', 'Visar alla uppladdade underlag att välja mellan.']],
    errors: [['Hittar inte underlaget', 'Kontrollera att det laddats upp och inte redan är kopplat.']],
    example: 'Koppla "faktura.pdf" till en ny verifikation innan du bokför.' }),

  a({ id: 'help-interpret', slug: 'tolka-underlag-med-ai', title: 'Tolka underlag med AI', category: 'Inkorg',
    keywords: ['tolka', 'ocr', 'ai', 'underlag', 'tolka underlaget'], related: ['vanliga-fel-ai-tolkning', 'ai-tolkning-fungerar', 'bokfora-kvitto'],
    summary: 'Låt AI läsa ut belopp, datum, moms och förslag på kontering.',
    purpose: 'Sparar tid: AI fyller i fält och föreslår kontering från underlaget.',
    when: 'När ett underlag är kopplat och du vill slippa skriva av det.',
    steps: ['Koppla underlaget.', 'Klicka Tolka underlaget.', 'Vänta några sekunder – fält och förslag fylls i.', 'Granska alltid värdena innan du bokför.'],
    fields: [['Konfidens per fält', 'Låga värden bör dubbelkollas mot bilden.']],
    errors: [['"AI-kvoten är tillfälligt slut"', 'Per-minut-gräns hos Google – vänta tills nedräkningen är klar och försök igen.'], ['Ingen dagskassa kunde läsas', 'Fyll i fälten manuellt – bilden kan vara svårläst.']],
    example: 'Tolka ett ICA-kvitto → netto, moms 12 %/25 % och konton föreslås.' }),

  a({ id: 'help-interpret-errors', slug: 'vanliga-fel-ai-tolkning', title: 'Vanliga fel vid AI-tolkning', category: 'Inkorg',
    keywords: ['fel', 'ai', 'tolkning', 'ocr', 'kvot'], related: ['tolka-underlag-med-ai', 'kvotfel-rate-limits', 'felsokning-ocr'],
    summary: 'De vanligaste orsakerna till att en tolkning blir fel eller uteblir.',
    purpose: 'Hjälper dig förstå och åtgärda tolkningsproblem.',
    when: 'När tolkningen ger konstiga värden eller inget svar.',
    steps: ['Kontrollera bildkvaliteten – suddiga/sneda bilder ger sämre resultat.', 'Verifiera momssatser och belopp mot underlaget.', 'Vid kvotfel: vänta och försök igen (appen byter modell automatiskt).'],
    fields: [],
    errors: [['Felaktig momssats utläst', 'Justera manuellt; kassadiff/öresutjämning fångar småfel.'], ['Z-rapport tolkas som inköp', 'Registrera som dagskassa i stället – det är egen försäljning.']],
    example: 'En suddig termo-Z-rapport kan kasta om 25 %/12 % – kontrollera per varugrupp.' }),

  a({ id: 'help-inbox-email', slug: 'epost-for-underlag', title: 'E-postadresser för underlag', category: 'Inkorg',
    keywords: ['e-post', 'mejl', 'inkommande', 'arkivnummer'], related: ['ladda-upp-underlag', 'epost-inkommande-underlag'],
    summary: 'Mejla in underlag direkt till företagets inkorg.',
    purpose: 'Underlag som skickas till företagets adress hamnar automatiskt i Inkorgen och klassas.',
    when: 'När leverantörer mejlar fakturor eller du vidarebefordrar kvitton.',
    steps: ['Hämta företagets inkorgsadress under Inställningar.', 'Vidarebefordra eller be leverantören skicka dit.', 'Bilagor läses in, OCR-tolkas och sorteras.'],
    fields: [['Adressformat', 'Mönstret är {arkivnummer}underlag@bokpilot.se.']],
    errors: [['Mejlet kom inte in', 'Adressen måste matcha företagets arkivnummer exakt.']],
    example: 'Skicka till `8063151underlag@bokpilot.se` så hamnar bilagan i rätt företags inkorg.' }),

  // ─────────────────────────── Bokföring ───────────────────────────
  a({ id: 'help-verifikation', slug: 'skapa-verifikation', title: 'Skapa verifikation', category: 'Bokföring',
    keywords: ['verifikation', 'bokföra', 'kontering', 'debet', 'kredit'], related: ['bokfora-kvitto', 'registrera-dagskassa', 'vanliga-bokforingsfel', 'stam-av-konto'],
    summary: 'Bokför en affärshändelse med balanserade konteringsrader.',
    purpose: 'Verifikationen är grunden i bokföringen: debet = kredit, kopplad till underlag.',
    when: 'När du ska bokföra något manuellt eller från ett tolkat underlag.',
    steps: ['Gå till Bokföring → Skapa verifikation.', 'Välj datum och beskrivning.', 'Koppla underlag och klicka Tolka för förslag, eller fyll i raderna själv.', 'Kontrollera att Differens = 0,00.', 'Klicka Bokför.'],
    fields: [['Bokföringsdatum', 'Måste ligga inom öppet räkenskapsår.'], ['Debet/Kredit', 'Summorna måste vara lika (differens 0).']],
    errors: [['"Differensen måste vara 0"', 'Justera raderna tills debet = kredit.'], ['Konto saknas i kontoplanen', 'Lägg upp kontot under Inställningar → Kontoplan.']],
    example: 'Debet 5410 Förbrukningsinventarier 800, debet 2640 moms 200, kredit 1930 1 000.' }),

  a({ id: 'help-receipt', slug: 'bokfora-kvitto', title: 'Bokföra kvitto', category: 'Bokföring',
    keywords: ['kvitto', 'utlägg', 'registrera kvitto', 'moms'], related: ['skapa-verifikation', 'tolka-underlag-med-ai', 'registrera-dagskassa'],
    summary: 'Registrera ett inköpskvitto som betalats på plats.',
    purpose: 'Bokför kostnaden + ingående moms och hur det betalats (kort/kontant).',
    when: 'När företaget köpt något och betalat direkt.',
    steps: ['Gå till Bokföring → Registrera kvitto.', 'Koppla kvittobilden och klicka Tolka underlaget.', 'Kontrollera kostnadskonto, moms och betalsätt.', 'Bokför.'],
    fields: [['Kostnadskonto', 'Väljs efter köpets art, inte butikens namn.'], ['Ingående moms', '2640, delas per momssats.'], ['Betalsätt', '1910 Kassa eller 1930 Företagskonto.']],
    errors: [['Moms stämmer inte', 'Kontrollera momssatsen (25/12/6 %) mot kvittot.'], ['Bilden tolkas inte', 'Felet beror oftast på kvot/bildkvalitet – inte att underlaget är fel.']],
    example: 'Biltema-kvitto 249 kr → debet 5410, debet 2640, kredit 1930.' }),

  a({ id: 'help-dagskassa', slug: 'registrera-dagskassa', title: 'Registrera dagskassa', category: 'Bokföring',
    keywords: ['dagskassa', 'z-rapport', 'kassaförsäljning', 'kassadiff', 'kontant', 'kort'], related: ['bokfora-kvitto', 'skapa-verifikation'],
    summary: 'Bokför butikens/onlineförsäljningens dagskassa.',
    purpose: 'Registrerar egen försäljning (utgående moms) per varugrupp och betalsätt; kassadifferens hamnar på 3790.',
    when: 'Vid daglig kassaredovisning från Z-rapport/kassaregister.',
    steps: ['Gå till Bokföring → Registrera dagskassa.', 'Koppla Z-rapporten och klicka Tolka underlaget (fyller varugrupper, moms, kontant, kort).', 'Kontrollera beloppen per momssats.', 'Ev. kassadiff visas och bokförs på 3790.', 'Bokför.'],
    fields: [['Varugrupp 25/12/6/0 %', 'Försäljning exkl. moms per sats.'], ['Kontant/Kort', '1910 respektive 1580.'], ['Kassadiff', 'Inbetalt − (försäljning + moms) → konto 3790.']],
    errors: [['Z-rapport tolkas som kvitto/inköp', 'Det är egen försäljning – registrera som dagskassa, inte kvitto.'], ['Stor kassadiff', 'Kontrollera beloppen; appen kräver bekräftelse vid väsentlig differens.']],
    example: 'Försäljning 25 % 1 000, moms 250, kort 1 250 → balanserad dagskassa.' }),

  a({ id: 'help-reconcile-account', slug: 'stam-av-konto', title: 'Stäm av konto', category: 'Bokföring',
    keywords: ['stäm av', 'avstämning', 'konto', 'saldo'], related: ['skapa-verifikation', 'avstamning'],
    summary: 'Kontrollera att ett kontos saldo stämmer mot underlag.',
    purpose: 'Avstämning säkrar att bokföringen är riktig inför bokslut och moms.',
    when: 'Vid period-/månadsavslut eller när ett saldo ser fel ut.',
    steps: ['Gå till Bokföring → Stäm av konto.', 'Välj konto och period.', 'Gå igenom transaktionerna mot underlag/kontoutdrag.', 'Markera avstämt.'],
    fields: [['Konto', 'T.ex. 1930, 2640.'], ['Period', 'Månad eller räkenskapsår.']],
    errors: [['Saldo stämmer inte', 'Sök saknad/dubblerad verifikation under Kontoanalys eller Sök belopp.']],
    example: 'Stäm av 1930 mot bankutdrag i slutet av månaden.' }),

  a({ id: 'help-periodisering', slug: 'periodisering', title: 'Periodisering', category: 'Bokföring',
    keywords: ['periodisering', 'förutbetald', 'upplupen', 'bokslut'], related: ['skapa-verifikation', 'vanliga-bokforingsfel'],
    summary: 'Fördela en kostnad eller intäkt över rätt period.',
    purpose: 'Ger rättvisande resultat genom att hänföra belopp till rätt månad/år.',
    when: 'Vid t.ex. förskottsbetalda försäkringar, hyror eller årsavgifter.',
    steps: ['Bokför grundhändelsen.', 'Skapa periodiseringsverifikation som fördelar beloppet över perioderna.', 'Kontrollera att balans- och resultatkonton blir rätt.'],
    fields: [['Förutbetald kostnad', 'Tillgångskonto (17xx).'], ['Upplupen kostnad', 'Skuldkonto (29xx).']],
    errors: [['Hela kostnaden i fel månad', 'Periodisera om över rätt perioder.']],
    example: 'Försäkring 12 000 kr/år → 1 000 kr per månad.' }),

  a({ id: 'help-bookkeeping-errors', slug: 'vanliga-bokforingsfel', title: 'Vanliga bokföringsfel', category: 'Bokföring',
    keywords: ['fel', 'bokföring', 'differens', 'moms', 'rättelse'], related: ['skapa-verifikation', 'kontrollera-moms'],
    summary: 'Typiska misstag och hur du undviker dem.',
    purpose: 'Förebygger fel som annars upptäcks först vid moms eller bokslut.',
    when: 'Som checklista innan du bokför.',
    steps: ['Säkerställ debet = kredit.', 'Rätt momssats och rätt momskonto (ingående 2640 vs utgående 2611/2621/2631).', 'Rätt kostnadskonto efter affärshändelsens art.', 'Underlag kopplat.'],
    fields: [],
    errors: [['Moms på fel sida', 'Inköp = ingående (debet 2640). Försäljning = utgående (kredit 26x1).'], ['Bokfört utan underlag', 'Koppla underlag i efterhand via dokumentpanelen.']],
    example: 'Kreditfaktura bokförd som vanlig faktura → vänd konteringen.' }),

  // ─────────────────────────── Leverantörsfakturor ───────────────────────────
  a({ id: 'help-supplier-invoice-create', slug: 'skapa-leverantorsfaktura', title: 'Skapa leverantörsfaktura', category: 'Leverantörsfakturor',
    keywords: ['leverantörsfaktura', 'faktura', 'underlag', 'kontering', 'moms'], related: ['koppla-underlag', 'tolka-faktura-med-ai', 'kontera-leverantorsfaktura', 'kreditfaktura'],
    summary: 'Registrera en leverantörsfaktura som ska betalas senare.',
    purpose: 'Bokför kostnad + ingående moms mot leverantörsskuld (2440) och håller koll på förfallodatum.',
    when: 'När du fått en faktura ställd till företaget.',
    steps: ['Gå till Leverantörsfakturor → Skapa leverantörsfaktura.', 'Välj leverantör.', 'Koppla underlaget och klicka Tolka för förslag.', 'Kontrollera total, moms och förfallodatum.', 'Bokför.'],
    fields: [['Leverantör', 'Väljs från registret; styr inlärd kontering.'], ['Förfallodatum', 'När fakturan ska betalas.'], ['2440 Leverantörsskulder', 'Krediteras med totalbeloppet.']],
    errors: [['Differens i konteringen', 'Netto + moms måste = totalbeloppet (öresutjämning på 3740).'], ['Dubbelräknad kostnad', 'Använd delsumman, inte både rader och delsumma.']],
    example: 'Faktura 1 250 kr (250 moms) → debet kostnad 1 000, debet 2640 250, kredit 2440 1 250.' }),

  a({ id: 'help-couple-underlag', slug: 'koppla-underlag', title: 'Koppla underlag', category: 'Leverantörsfakturor',
    keywords: ['koppla', 'underlag', 'bild', 'leverantörsfaktura'], related: ['skapa-leverantorsfaktura', 'koppla-bild-till-faktura'],
    summary: 'Knyt fakturabilden till leverantörsfakturan.',
    purpose: 'Krav på spårbarhet – fakturan ska ha sitt underlag.',
    when: 'När du skapar eller kompletterar en leverantörsfaktura.',
    steps: ['Öppna dokumentpanelen (Koppla bild).', 'Välj underlaget i rullistan eller bläddra i inkorgen.', 'Klicka Koppla.'],
    fields: [],
    errors: [['Underlaget redan kopplat någon annanstans', 'Ladda upp en kopia eller koppla bort från den andra posten.']],
    example: 'Koppla "grenke.pdf" till fakturan innan du bokför.' }),

  a({ id: 'help-interpret-invoice', slug: 'tolka-faktura-med-ai', title: 'Tolka faktura med AI', category: 'Leverantörsfakturor',
    keywords: ['tolka', 'ai', 'ocr', 'faktura', 'kontering'], related: ['skapa-leverantorsfaktura', 'tolka-underlag-med-ai', 'vanliga-fel-ai-tolkning'],
    summary: 'Läs ut leverantör, belopp, moms och förslag på kontering automatiskt.',
    purpose: 'Snabbar upp registrering och minskar fel vid avskrift.',
    when: 'När underlaget är kopplat.',
    steps: ['Koppla fakturan.', 'Klicka Tolka underlaget.', 'Granska leverantör, fakturanummer, OCR, datum, total och moms.', 'Justera vid behov och bokför.'],
    fields: [['OCR-nummer', 'Betalreferens – förväxla inte med fakturanummer.'], ['Kreditfaktura', 'Upptäcks automatiskt och vänder konteringen.']],
    errors: [['Kreditvillkor tolkas som kreditfaktura', 'Endast "kreditnota/kreditfaktura/att erhålla" = kreditfaktura.']],
    example: 'Tolkning fyller leverantör "Grenkeleasing AB", förfallodatum och moms.' }),

  a({ id: 'help-supplier-coding', slug: 'kontera-leverantorsfaktura', title: 'Kontera leverantörsfaktura', category: 'Leverantörsfakturor',
    keywords: ['kontering', 'konto', 'leverantörsfaktura', 'inlärd regel'], related: ['skapa-leverantorsfaktura', 'kreditfaktura'],
    summary: 'Välj rätt kostnadskonton för fakturan.',
    purpose: 'Rätt konton ger rätt resultat och moms. BokPilot lär sig återkommande mönster per leverantör.',
    when: 'När du registrerar fakturan.',
    steps: ['Efter tolkning – kontrollera föreslagna konton.', 'Använd "Kontering från förra fakturan" för återkommande leverantörer.', 'Säkerställ differens 0.'],
    fields: [['Inlärd regel', 'Föreslås automatiskt utifrån leverantörens historik.']],
    errors: [['Fel kostnadskonto', 'Ändra raden – nästa gång lär sig appen det nya mönstret.']],
    example: 'Hyra → 5010/5220 enligt tidigare kontering.' }),

  a({ id: 'help-credit-invoice', slug: 'kreditfaktura', title: 'Kreditfaktura', category: 'Leverantörsfakturor',
    keywords: ['kreditfaktura', 'kreditnota', 'återbetalning'], related: ['skapa-leverantorsfaktura', 'kontera-leverantorsfaktura'],
    summary: 'Hantera en kreditfaktura med omvänd kontering.',
    purpose: 'En kreditfaktura minskar en tidigare kostnad/skuld.',
    when: 'När du fått en kreditnota från leverantören.',
    steps: ['Registrera fakturan – kryssrutan Kreditfaktura markeras automatiskt vid tolkning.', 'Total och moms visas negativa.', 'Konteringen vänds: debet 2440, kredit kostnad/moms.', 'Bokför.'],
    fields: [['Kreditfaktura (kryssruta)', 'Vänder tecken och konteringssidor.']],
    errors: [['Dubbel negation', 'Om OCR redan gav negativa belopp – dubbelnegera inte.']],
    example: 'Kreditnota −1 458 kr → debet 2440 1 458, kredit kostnad/moms.' }),

  a({ id: 'help-pay-supplier', slug: 'betala-leverantorsfaktura', title: 'Betala leverantörsfaktura', category: 'Leverantörsfakturor',
    keywords: ['betala', 'betalning', 'leverantörsskuld', 'bankgiro'], related: ['skapa-leverantorsfaktura', 'matcha-betalningar'],
    summary: 'Markera fakturan som betald och bokför betalningen.',
    purpose: 'Reglerar leverantörsskulden (2440) mot bank (1930).',
    when: 'När fakturan betalats från banken.',
    steps: ['Öppna fakturan.', 'Registrera betalning med datum och belopp.', 'Eller matcha mot en importerad bankhändelse i Kassa och bank.'],
    fields: [['2440', 'Debiteras vid betalning.'], ['1930', 'Krediteras.']],
    errors: [['Betald men kvar som obetald', 'Matcha mot bankhändelsen eller registrera betalningen manuellt.']],
    example: 'Betalning 1 250 kr → debet 2440, kredit 1930.' }),

  a({ id: 'help-supplier-errors', slug: 'vanliga-fel-leverantorsfaktura', title: 'Vanliga fel', category: 'Leverantörsfakturor',
    keywords: ['fel', 'leverantörsfaktura', 'moms', 'differens'], related: ['skapa-leverantorsfaktura', 'kreditfaktura'],
    summary: 'Vanliga misstag på leverantörsfakturor.',
    purpose: 'Undvik moms- och differensfel.',
    when: 'Som checklista före bokföring.',
    steps: ['Kontrollera leverantör och förfallodatum.', 'Netto + moms = total.', 'Öresutjämning på 3740 vid behov.'],
    fields: [],
    errors: [['Fakturanummer/OCR förväxlade', 'Kontrollera fälten – de har olika syfte.'], ['Fel momssats', 'Justera mot fakturans momsspecifikation.']],
    example: 'Spiris-fakturan dubbelräknades – använd delsumman.' }),

  // ─────────────────────────── Kundfakturor ───────────────────────────
  a({ id: 'help-invoice-create', slug: 'skapa-kundfaktura', title: 'Skapa kundfaktura', category: 'Kundfakturor',
    keywords: ['kundfaktura', 'faktura', 'fakturera', 'moms', 'artikel'], related: ['skicka-faktura', 'kreditera-kundfaktura', 'fakturamallar'],
    summary: 'Skapa och bokför en faktura till en kund.',
    purpose: 'Fakturerar försäljning med utgående moms och kundfordran (1510).',
    when: 'När du sålt en vara eller tjänst.',
    steps: ['Gå till Kundfakturor → Ny faktura.', 'Välj kund.', 'Lägg till artiklar/rader med pris och momssats.', 'Kontrollera summor och förfallodatum.', 'Spara/Bokför.'],
    fields: [['Kund', 'Från kundregistret.'], ['Momssats', '25/12/6/0 % per rad.'], ['Förfallodatum', 'Styr påminnelser.']],
    errors: [['Fel momssats på rad', 'Ändra raden innan du skickar.']],
    example: 'Konsultarvode 10 000 + 25 % moms → 12 500 kr att betala.' }),

  a({ id: 'help-invoice-send', slug: 'skicka-faktura', title: 'Skicka faktura', category: 'Kundfakturor',
    keywords: ['skicka', 'e-post', 'faktura', 'pdf'], related: ['skapa-kundfaktura', 'e-faktura', 'paminnelser'],
    summary: 'Skicka fakturan till kunden.',
    purpose: 'Levererar fakturan som PDF/e-post eller e-faktura.',
    when: 'När fakturan är klar.',
    steps: ['Öppna fakturan.', 'Välj Skicka.', 'Kontrollera mottagaradress och skicka.'],
    fields: [['Mottagare', 'Kundens e-post.']],
    errors: [['Fakturan kom inte fram', 'Kontrollera e-postadressen i kundregistret.']],
    example: 'Skicka faktura som PDF till kundens ekonomiavdelning.' }),

  a({ id: 'help-invoice-credit', slug: 'kreditera-kundfaktura', title: 'Kreditera kundfaktura', category: 'Kundfakturor',
    keywords: ['kreditera', 'kreditfaktura', 'kund'], related: ['skapa-kundfaktura'],
    summary: 'Skapa en kreditfaktura mot en tidigare kundfaktura.',
    purpose: 'Annullerar eller minskar en fakturerad summa.',
    when: 'Vid retur, prisjustering eller felfakturering.',
    steps: ['Öppna ursprungsfakturan.', 'Välj Kreditera.', 'Justera ev. belopp och bokför.'],
    fields: [],
    errors: [['Krediterar fel faktura', 'Kontrollera fakturanummer först.']],
    example: 'Kreditera hela fakturan vid retur av vara.' }),

  a({ id: 'help-invoice-templates', slug: 'fakturamallar', title: 'Fakturamallar', category: 'Kundfakturor',
    keywords: ['mall', 'fakturamall', 'layout', 'logotyp'], related: ['skapa-kundfaktura'],
    summary: 'Anpassa fakturans utseende och standardtexter.',
    purpose: 'Enhetliga, professionella fakturor.',
    when: 'Vid uppstart eller när du vill ändra layout.',
    steps: ['Gå till Inställningar (fakturamallar).', 'Lägg in logotyp, betalvillkor och texter.', 'Spara.'],
    fields: [['Betalvillkor', 'T.ex. 30 dagar netto.']],
    errors: [],
    example: 'Lägg in företagets logotyp på alla fakturor.' }),

  a({ id: 'help-einvoice', slug: 'e-faktura', title: 'E-faktura', category: 'Kundfakturor',
    keywords: ['e-faktura', 'elektronisk', 'peppol'], related: ['skicka-faktura', 'skapa-kundfaktura'],
    summary: 'Skicka elektroniska fakturor till företag/offentlig sektor.',
    purpose: 'E-faktura krävs ofta av offentliga kunder.',
    when: 'När kunden begär e-faktura.',
    steps: ['Säkerställ att kundens org.nr och e-fakturauppgifter finns.', 'Välj e-faktura vid utskick.'],
    fields: [['Org.nr', 'Krävs för e-faktura.']],
    errors: [['E-faktura nekas', 'Kontrollera kundens elektroniska adress/uppgifter.']],
    example: 'Skicka e-faktura till en kommun.' }),

  a({ id: 'help-reminders', slug: 'paminnelser', title: 'Påminnelser', category: 'Kundfakturor',
    keywords: ['påminnelse', 'förfallen', 'betalning', 'krav'], related: ['skapa-kundfaktura', 'skicka-faktura'],
    summary: 'Påminn kunder om obetalda fakturor.',
    purpose: 'Snabbare betalt genom att följa upp förfallna fakturor.',
    when: 'När en faktura passerat förfallodatum.',
    steps: ['Identifiera förfallna fakturor i listan.', 'Skicka påminnelse.'],
    fields: [],
    errors: [['Påminnelse på betald faktura', 'Matcha betalningen först så markeras fakturan som betald.']],
    example: 'Skicka påminnelse på faktura 5 dagar efter förfall.' }),

  // ─────────────────────────── Kassa och bank ───────────────────────────
  a({ id: 'help-bank-import', slug: 'importera-bankhandelser', title: 'Importera bankhändelser', category: 'Kassa och bank',
    keywords: ['bank', 'import', 'transaktioner', 'kontoutdrag'], related: ['matcha-betalningar', 'avstamning', 'bankkonto'],
    summary: 'Läs in transaktioner från banken.',
    purpose: 'Underlag för matchning och avstämning mot bokföringen.',
    when: 'Löpande, t.ex. veckovis.',
    steps: ['Gå till Kassa och bank.', 'Importera fil från banken eller lägg in transaktioner.', 'Granska de inlästa raderna.'],
    fields: [['Bankkonto', 'Vilket konto importen gäller.']],
    errors: [['Dubbla transaktioner', 'Kontrollera att samma period inte importerats två gånger.']],
    example: 'Importera kontoutdrag för 1930 för maj.' }),

  a({ id: 'help-match-payments', slug: 'matcha-betalningar', title: 'Matcha betalningar', category: 'Kassa och bank',
    keywords: ['matcha', 'betalning', 'avprickning', 'faktura'], related: ['importera-bankhandelser', 'betala-leverantorsfaktura', 'avstamning'],
    summary: 'Koppla bankhändelser mot fakturor och verifikationer.',
    purpose: 'Markerar fakturor som betalda och håller banksaldot rätt.',
    when: 'Efter import av bankhändelser.',
    steps: ['Öppna en bankhändelse.', 'Matcha mot rätt faktura/verifikation.', 'Bekräfta.'],
    fields: [],
    errors: [['Hittar ingen match', 'Kontrollera belopp/datum eller bokför händelsen manuellt.']],
    example: 'Matcha inbetalning 12 500 kr mot kundfaktura.' }),

  a({ id: 'help-reconciliation', slug: 'avstamning', title: 'Avstämning', category: 'Kassa och bank',
    keywords: ['avstämning', 'saldo', 'bank', 'differens'], related: ['matcha-betalningar', 'stam-av-konto', 'vanliga-differenser'],
    summary: 'Stäm av banksaldot mot bokföringen.',
    purpose: 'Säkerställer att bokfört saldo = verkligt banksaldo.',
    when: 'Vid månads-/periodavslut.',
    steps: ['Jämför bokfört saldo på 1930 mot bankutdraget.', 'Reda ut differenser (omatchade poster).', 'Markera avstämt.'],
    fields: [],
    errors: [['Differens kvar', 'Sök omatchade eller felbokförda poster.']],
    example: 'Banksaldo och 1930 ska vara lika vid månadsskifte.' }),

  a({ id: 'help-bank-account', slug: 'bankkonto', title: 'Bankkonto', category: 'Kassa och bank',
    keywords: ['bankkonto', 'kassa', 'konto', 'inställning'], related: ['importera-bankhandelser', 'grundinstallningar'],
    summary: 'Lägg upp och hantera kassa-/bankkonton.',
    purpose: 'Kopplar bokföringskonton (1910/1930) till verkliga konton.',
    when: 'Vid uppstart eller nytt bankkonto.',
    steps: ['Gå till Inställningar → Kassa-/bankkonton.', 'Lägg till konto med kontonummer och bokföringskonto.', 'Spara.'],
    fields: [['Bokföringskonto', '1910 Kassa eller 1930 Företagskonto.']],
    errors: [],
    example: 'Koppla företagets bankkonto till 1930.' }),

  a({ id: 'help-bank-diffs', slug: 'vanliga-differenser', title: 'Vanliga differenser', category: 'Kassa och bank',
    keywords: ['differens', 'avstämning', 'fel'], related: ['avstamning', 'matcha-betalningar'],
    summary: 'Vanliga orsaker till att banken inte stämmer.',
    purpose: 'Snabbare felsökning vid avstämning.',
    when: 'När avstämningen inte går ihop.',
    steps: ['Leta omatchade bankhändelser.', 'Kontrollera dubbletter och fel datum.', 'Kontrollera öresavrundningar.'],
    fields: [],
    errors: [['Saknad inbetalning', 'Bokför/matcha händelsen.'], ['Avgift ej bokförd', 'Bokför bankavgiften.']],
    example: 'Bankavgift 50 kr saknades i bokföringen → bokför mot 6570.' }),

  // ─────────────────────────── Kontoanalys ───────────────────────────
  a({ id: 'help-account-analysis', slug: 'kontoanalys-oversikt', title: 'Kontoanalys', category: 'Kontoanalys',
    keywords: ['kontoanalys', 'konto', 'transaktioner', 'saldo', 'sök belopp'], related: ['stam-av-konto', 'rapport-huvudbok'],
    summary: 'Granska ett kontos transaktioner och saldon.',
    purpose: 'Borrar ner i enskilda konton för analys och felsökning.',
    when: 'När du vill förstå vad som ligger bakom ett saldo.',
    steps: ['Öppna Kontoanalys.', 'Välj konto och period.', 'Klicka på en rad för att se verifikationen.'],
    fields: [['Period', 'Månad eller år.']],
    errors: [['Oväntat saldo', 'Sök efter fel-/dubbelbokningar bland transaktionerna.']],
    example: 'Analysera 2640 för att se ingående moms per månad.' }),

  // ─────────────────────────── Lön ───────────────────────────
  a({ id: 'help-payroll-overview', slug: 'hantera-loner-och-anstallda', title: 'Hantera löner och anställda', category: 'Lön',
    keywords: ['lön', 'anställda', 'lönekörning', 'personal'], related: ['lagg-till-anstalld', 'skapa-lonekorning', 'granska-lon', 'bokfor-lon'],
    summary: 'Översikt över lönemodulen: Löner och Anställda.',
    purpose: 'Lägg upp anställda och kör lön (period → anställda → granska & bokför).',
    when: 'När företaget har anställda.',
    steps: ['Öppna Lön i sidomenyn.', 'Fliken Anställda: lägg upp personal.', 'Fliken Löner: skapa lönekörning.'],
    fields: [['Anställda', 'Krävs innan en lönekörning kan göras.']],
    errors: [['"Inga aktiva anställda hittades"', 'Lägg till anställda under fliken Anställda först.']],
    example: 'Lägg upp en anställd och kör månadslön för juni.' }),

  a({ id: 'help-add-employee', slug: 'lagg-till-anstalld', title: 'Lägg till anställd', category: 'Lön',
    keywords: ['anställd', 'personal', 'personnummer', 'månadslön', 'skattetabell'], related: ['hantera-loner-och-anstallda', 'skapa-lonekorning'],
    summary: 'Lägg upp en anställd i registret.',
    purpose: 'Anställda är grunden för lönekörningar och arbetsgivardeklaration.',
    when: 'Innan första lönekörningen, och vid nyanställning.',
    steps: ['Lön → Anställda → Ny anställd.', 'Fyll i Personuppgifter (namn, personnummer).', 'Anställningsuppgifter (startdatum, aktiv).', 'Löneinformation (bruttolön/månad, ev. sidoinkomst, kommun/skattetabell, bankkonto).', 'Ev. ingående ackumulerade värden vid byte av system.', 'Skapa.'],
    fields: [['Personnummer', 'Valideras (Luhn). Känslig uppgift – GDPR.'], ['Bruttolön/månad', 'Lön före skatt.'], ['Sidoinkomst', 'Fast %-skatt i stället för skattetabell.'], ['Undanta arbetsgivaravgifter', 'Avgift beräknas ej för denna anställd.']],
    errors: [['Ogiltigt personnummer', 'Kontrollsiffran stämmer inte – kontrollera siffrorna.'], ['Skattetabell saknas', 'Anges manuellt utifrån Skatteverkets tabell för kommunen.']],
    example: 'Anna Andersson, 35 000 kr/mån, tillsvidare, aktiv.' }),

  a({ id: 'help-payroll-run', slug: 'skapa-lonekorning', title: 'Skapa lönekörning', category: 'Lön',
    keywords: ['lönekörning', 'lön', 'period', 'bruttolön'], related: ['lagg-till-anstalld', 'granska-lon', 'bokfor-lon'],
    summary: 'Kör lön för en period.',
    purpose: 'Beräknar netto och avgifter och förbereder bokföring och utbetalning.',
    when: 'En gång per löneperiod (oftast månadsvis).',
    steps: ['Lön → Löner → Ny lönekörning.', 'Välj period (år och månad).', 'Välj anställda.', 'Ange bruttolön/preliminärskatt och granska.', 'Bokför.'],
    fields: [['Period', 'År och månad.'], ['Bruttolön', 'Lön före skatt.'], ['Arbetsgivaravgift', 'Beräknas (31,42 % som standard).']],
    errors: [['Inga anställda att välja', 'Lägg till aktiva anställda först.']],
    example: 'Lönekörning juni 2026 för en anställd.' }),

  a({ id: 'help-payroll-review', slug: 'granska-lon', title: 'Granska lön', category: 'Lön',
    keywords: ['granska', 'lön', 'netto', 'kontroll'], related: ['skapa-lonekorning', 'bokfor-lon'],
    summary: 'Kontrollera lönekörningen innan bokföring.',
    purpose: 'Säkrar rätt brutto, skatt, avgifter och netto.',
    when: 'Innan du bokför lönekörningen.',
    steps: ['Öppna lönekörningen.', 'Kontrollera per anställd: brutto, skatt, netto.', 'Kontrollera arbetsgivaravgifter.', 'Gå vidare till Bokför.'],
    fields: [['Nettolön', 'Utbetalas till den anställde.']],
    errors: [['Fel skatt', 'Kontrollera skattetabell/sidoinkomst på den anställde.']],
    example: 'Brutto 35 000, skatt enligt tabell, netto till bankkonto.' }),

  a({ id: 'help-payroll-book', slug: 'bokfor-lon', title: 'Bokför lön', category: 'Lön',
    keywords: ['bokför', 'lön', 'arbetsgivaravgift', 'personalskatt'], related: ['skapa-lonekorning', 'granska-lon', 'vanliga-lonefel'],
    summary: 'Bokför lönekörningen.',
    purpose: 'Skapar verifikation för lön, skatt och arbetsgivaravgifter.',
    when: 'Efter granskning.',
    steps: ['Välj Bokför i lönekörningen.', 'Kontrollera konteringen.', 'Bokför.'],
    fields: [['7010 Löner', 'Debet brutto.'], ['2710 Personalskatt', 'Kredit avdragen skatt.'], ['7510/2731 Arbetsgivaravgifter', 'Kostnad respektive skuld.'], ['1930', 'Kredit nettoutbetalning.']],
    errors: [['Differens i lönekonteringen', 'Kontrollera att brutto = netto + skatt och att avgifter balanserar.']],
    example: 'Brutto 35 000 → 7010 debet, 2710 + 1930 kredit, 7510/2731 för avgifter.' }),

  a({ id: 'help-payroll-errors', slug: 'vanliga-lonefel', title: 'Vanliga lönefel', category: 'Lön',
    keywords: ['fel', 'lön', 'skatt', 'avgift'], related: ['lagg-till-anstalld', 'bokfor-lon'],
    summary: 'Vanliga misstag i lönehanteringen.',
    purpose: 'Undvik fel i skatt, avgifter och utbetalning.',
    when: 'Som checklista.',
    steps: ['Kontrollera personnummer och skattetabell.', 'Stäm av brutto/skatt/netto.', 'Kontrollera arbetsgivaravgift och ev. undantag.'],
    fields: [],
    errors: [['Fel arbetsgivaravgift', 'Kontrollera om åldersnedsättning eller undantag gäller.'], ['Fel bankkonto', 'Uppdatera den anställdes kontonummer.']],
    example: 'Pensionär kan ha lägre arbetsgivaravgift – kontrollera satsen.' }),

  // ─────────────────────────── Moms ───────────────────────────
  a({ id: 'help-vat-report', slug: 'momsrapport', title: 'Momsrapport', category: 'Moms',
    keywords: ['moms', 'momsrapport', 'deklaration', 'skatteverket'], related: ['kontrollera-moms', 'bokfora-moms', 'vanliga-momsavvikelser'],
    summary: 'Ta fram momsrapporten för perioden.',
    purpose: 'Underlag för momsdeklaration till Skatteverket.',
    when: 'Vid varje momsperiod (månad/kvartal/år).',
    steps: ['Gå till Moms.', 'Välj period.', 'Granska utgående och ingående moms.', 'Stäm av mot bokföringen.'],
    fields: [['Utgående moms', '2611/2621/2631.'], ['Ingående moms', '2640.']],
    errors: [['Moms stämmer inte med resultatet', 'Kontrollera att moms bokförts mot rätt konto och sats.']],
    example: 'Momsrapport för Q2 visar moms att betala/återfå.' }),

  a({ id: 'help-vat-check', slug: 'kontrollera-moms', title: 'Kontrollera moms', category: 'Moms',
    keywords: ['moms', 'kontroll', 'avstämning', 'granskning'], related: ['momsrapport', 'vanliga-momsavvikelser', 'ai-granskning-oversikt'],
    summary: 'Hitta momsfel innan deklaration.',
    purpose: 'Säkrar att momsen är rätt bokförd – AI-granskning kan hjälpa till.',
    when: 'Före momsdeklaration.',
    steps: ['Kör momskontrollen/AI-granskningen.', 'Gå igenom flaggade poster.', 'Rätta felen och kontrollera igen.'],
    fields: [],
    errors: [['Moms saknas på en post', 'Komplettera konteringen med rätt momskonto.'], ['Fel momssats', 'Justera mot underlaget.']],
    example: 'Granskningen flaggar en faktura där moms saknas på 2640.' }),

  a({ id: 'help-vat-book', slug: 'bokfora-moms', title: 'Bokföra moms', category: 'Moms',
    keywords: ['bokföra moms', 'momsredovisning', 'redovisningskonto'], related: ['momsrapport', 'kontrollera-moms'],
    summary: 'Boka om momsen vid periodens slut.',
    purpose: 'Nollar momskonton mot momsredovisningskontot (2650) och skuld/fordran.',
    when: 'När momsperioden stängs.',
    steps: ['Ta fram momsrapporten.', 'Skapa momsverifikationen som bokar om moms.', 'Kontrollera saldon.'],
    fields: [['2650 Momsredovisning', 'Skuld eller fordran.']],
    errors: [['Momskonton inte nollade', 'Bokför omföringen för perioden.']],
    example: 'Utgående − ingående = moms att betala → 2650.' }),

  a({ id: 'help-vat-deviations', slug: 'vanliga-momsavvikelser', title: 'Vanliga momsavvikelser', category: 'Moms',
    keywords: ['moms', 'avvikelse', 'fel', 'kontroll'], related: ['kontrollera-moms', 'momsrapport'],
    summary: 'Typiska momsfel och hur de upptäcks.',
    purpose: 'Förebygger fel i momsdeklarationen.',
    when: 'Som checklista före deklaration.',
    steps: ['Kontrollera momssatser per post.', 'Kontrollera ingående vs utgående.', 'Kontrollera omvänd skattskyldighet/EU-handel.'],
    fields: [],
    errors: [['Moms på kvitto utan giltigt underlag', 'Dra inte moms utan korrekt kvitto/faktura.'], ['Fel sats', 'Justera mot underlaget.']],
    example: 'Representation har begränsad avdragsrätt – kontrollera momsen.' }),

  // ─────────────────────────── Månadskontroll ───────────────────────────
  a({ id: 'help-monthly-control', slug: 'manadskontroll', title: 'Månadskontroll', category: 'Månadskontroll',
    keywords: ['månadskontroll', 'månadsavslut', 'periodavslut', 'kontroll', 'checklista', 'avstämning'],
    related: ['skapa-verifikation', 'importera-bankhandelser', 'momsrapport'],
    summary: 'Hitta och åtgärda allt som måste vara klart innan månaden kan stängas.',
    purpose: 'Månadskontroll samlar ofullständiga moment – okopplade underlag, obalanserade verifikationer, ej bokförda eller förfallna fakturor, omatchade bankhändelser m.m. – i en prioriterad lista per månad.',
    when: 'Vid månadsavslut, eller löpande för att hålla bokföringen i ordning.',
    steps: ['Gå till Månadskontroll i sidomenyn.', 'Välj månad högst upp.', 'Klicka "Kör månadskontroll" för att analysera perioden.', 'Arbeta uppifrån – kritiska (röda) punkter först.', 'Öppna en punkt för detaljer, "Gå till" rätt vy, eller be AI om hjälp.', 'Markera som påbörjad/löst, eller ignorera med motivering.'],
    fields: [['Prioritet', 'Kritisk (röd) blockerar avslut, Hög (orange), Normal (blå), Låg (grå).'], ['Status per område', 'Antal öppna punkter per modul – klicka för att filtrera.'], ['Progress', 'Andel åtgärdade punkter för månaden.'], ['Badge i menyn', 'Antal kritiska (röd) eller höga (orange) öppna punkter.']],
    errors: [['En punkt gäller inte längre', 'Kör kontrollen igen – punkter som inte längre stämmer löses automatiskt.'], ['Vill inte åtgärda en punkt', 'Ignorera den med motivering så är beslutet spårbart.'], ['Osäker på varför en punkt uppstod', 'Öppna punkten och välj "Be AI om hjälp".']],
    example: 'I juni: 1 obalanserad verifikation (kritisk) och 4 okopplade underlag (hög) – du åtgärdar dem och progress går mot 100 %.' }),

  // ─────────────────────────── AI Bokslut & Årsredovisning ───────────────────────────
  a({ id: 'help-ai-bokslut', slug: 'ai-bokslut-arsredovisning', title: 'AI Bokslut & Årsredovisning', category: 'AI Bokslut & Årsredovisning',
    keywords: ['bokslut', 'årsredovisning', 'k2', 'bokslutskontroll', 'riskanalys', 'årsbokslut', 'redovisningskonsult', 'ai-paket'],
    related: ['manadskontroll', 'skapa-verifikation', 'momsrapport'],
    summary: 'AI-stött arbetsflöde som hjälper dig förbereda bokslut och K2-årsredovisning – det analyserar, kontrollerar, riskbedömer och föreslår. Du granskar och beslutar alltid själv.',
    purpose: 'Funktionen snabbar upp bokslutsarbetet genom att analysera bokföringen, bygga en bokslutschecklista och flagga risker/avvikelser. Den BOKFÖR ALDRIG, ÄNDRAR ALDRIG låsta perioder och LÄMNAR ALDRIG IN årsredovisningen. Allt AI-/automatiserat underlag är förslag som måste granskas och godkännas av redovisningskonsult, som har det slutliga ansvaret.',
    when: 'Vid årsbokslut och årsredovisning (K2 för mindre aktiebolag). Kräver att funktionen ingår i din plan/licens (AI-paketet).',
    steps: [
      'Licens: saknas funktionen i din plan visas "ingår inte i din nuvarande plan" – kontakta BokPilot.',
      'Välj bolag (nere till vänster) och räkenskapsår högst upp på sidan.',
      'Klicka "Kör analys" – systemet LÄSER bokföringen för året och bygger/uppdaterar bokslutschecklistan med risknivåer (inga ändringar görs i bokföringen).',
      'Arbeta uppifrån: åtgärda kritiska och höga risker först. Öppna en kontrollpunkt för beskrivning, saldo, källa och "Gå till" rätt vy i appen.',
      'Markera punkter: Påbörja, Klar, Kräver granskning eller Ignorera (admin). Medlemmar kan tilldela och kommentera.',
      'Sätt övergripande status (admin): Klar för konsult, Godkänn, Avvisa eller Lås.',
      'Bokslutsbilagor: dokumentera avstämningar (bank, kund-/leverantörsreskontra, moms, skatt, anläggningar m.m.) med saldo enligt huvudbok, avstämt belopp och differens. "Föreslå bilagor" skapar utkast från kontrollerna. Bilagor är underlag – ingen automatisk bokföring.',
      'AI-förslag: klicka "Generera AI-förslag" för strukturerade granskningsförslag (risk, säkerhet, kopplad check/bilaga, nästa kontroll). Acceptera/avvisa/ignorera/markera som åtgärdad. AI bokför inte och skapar inga verifikationer – allt kräver din bedömning.',
      'Årsredovisningsutkast (K2): klicka "Skapa K2-utkast" för en strukturerad årsredovisning med sektionerna förvaltningsberättelse, resultaträkning, balansräkning, noter, fastställelseintyg och underskriftssida. Resultat- och balansräkning beräknas från bokföringen (huvudboken) – AI ändrar aldrig siffrorna. Öppna en sektion för att läsa/redigera text, se källreferenser och markera den som granskad, godkänd eller avvisad. "Uppdatera utkast" räknar om från senaste bokföringen.',
      'K2-utkastet: BokPilot skapar ingen PDF, lämnar INTE in årsredovisningen till Bolagsverket och godkänner ingenting automatiskt. Saknas jämförelsetal eller uppgift skrivs det ut tydligt ("Jämförelsetal saknas…" / "Uppgift saknas. Kräver manuell granskning."). Allt måste granskas och godkännas av behörig redovisningskonsult.',
      'Validera K2-utkastet: klicka "Validera utkast" för att se vad som är ofullständigt eller riskfyllt – saknade/ogranskade sektioner, obalanserad balansräkning, saknade jämförelsetal, öppna kritiska/höga kontroller, bilagor med differens, ogranskade AI-förslag och ofullständiga noter. Varje punkt har allvarlighetsgrad (kritisk/hög/varning/info), status och föreslagen åtgärd. Admin kan markera en punkt som löst eller ignorera den med motivering.',
      'Granskningsspärrar: utkastet kan inte godkännas så länge det finns öppna punkter med hög eller kritisk allvarlighetsgrad, och kan inte låsas så länge det finns öppna kritiska punkter. Åtgärda eller ignorera (med motivering) punkterna först. Valideringen är ett kontrollstöd – den ersätter inte redovisningskonsultens ansvar.',
      'AI-texter (förvaltningsberättelse och noter): klicka "Generera AI-texter" så formulerar AI textutkast för ENBART förvaltningsberättelse och noter, utifrån kända uppgifter. AI ändrar aldrig siffror, resultat- eller balansräkning, hittar inte på jämförelsetal, noter, ställda säkerheter eller eventualförpliktelser, och godkänner ingenting. Alla AI-texter markeras som AI-genererade och kräver granskning; i sektionen visas modell, prompt och tidpunkt. Redigerar du texten manuellt återställs sektionen till "kräver granskning". AI-texter är utkast och får inte användas utan mänsklig kontroll.',
      'Granska alltid AI-genererat underlag innan det används – konsulten godkänner och ansvarar.',
    ],
    fields: [
      ['Status: Ej påbörjad / Pågår', 'Inget gjort ännu / analys körd och arbete pågår.'],
      ['Status: Kräver granskning', 'Det finns öppna kritiska eller höga risker som måste hanteras.'],
      ['Status: Klar för konsult', 'Klart för redovisningskonsultens slutgranskning.'],
      ['Status: Godkänd / Avvisad', 'Konsultens beslut – loggas i spårbarheten.'],
      ['Status: Låst', 'Endast läsning. Inga ändringar, ingen ny analys, ingen statusändring.'],
      ['Risk: Kritisk (röd)', 'Blockerar ett korrekt bokslut, t.ex. att bokföringen inte balanserar. Åtgärda först.'],
      ['Risk: Hög (orange)', 'Viktig avvikelse, t.ex. omatchade bankhändelser eller ovanliga saldon.'],
      ['Risk: Medel (blå)', 'Bör stämmas av, t.ex. moms eller kontrollkonton.'],
      ['Risk: Låg (grå)', 'Mindre avvikelse/rekommendation, ofta för manuell bedömning.'],
      ['Behörighet', 'Admin markerar klar/ignorerar och ändrar status. Medlem kan läsa, köra analys, tilldela och kommentera.'],
      ['Audit & spårbarhet', 'Varje analys och åtgärd loggas (vem, när, vad). Nekade försök loggas internt för säkerhet.'],
      ['AI-/automatiserat underlag', 'Förslag och utkast som ALLTID måste granskas och godkännas av redovisningskonsult.'],
      ['Bokslutsbilagor', 'Avstämningsunderlag per område: saldo huvudbok, avstämt belopp och differens. Differens markeras rött. Endast admin skapar/ändrar/godkänner. Inget bokförs automatiskt.'],
      ['AI-förslag', 'Strukturerat granskningsstöd (risknivå, säkerhet, kopplad check/bilaga, föreslagen nästa kontroll). Endast admin genererar/granskar. Inget bokförs och inga verifikationer skapas – kräver mänsklig bedömning.'],
      ['Årsredovisningsutkast (K2)', 'Strukturerat utkast: förvaltningsberättelse, resultaträkning, balansräkning, noter, fastställelseintyg, underskriftssida. RR/BR beräknas från huvudboken (AI ändrar inte siffror); status per sektion (kräver granskning/granskad/godkänd/avvisad). Ingår INTE: PDF, e-inlämning till Bolagsverket, automatisk signering, K3. Allt kräver granskning och godkännande – BokPilot lämnar inte in något.'],
      ['Validering av K2-utkast', 'Deterministiska kontrollpunkter med allvarlighetsgrad (kritisk/hög/varning/info). Öppna höga/kritiska punkter blockerar godkännande; öppna kritiska blockerar låsning. Admin löser eller ignorerar (med motivering). Kontrollstöd – ersätter inte konsultens ansvar. Bygger inte PDF/inlämning/signering.'],
      ['AI-texter (förvaltningsberättelse/noter)', 'AI formulerar endast textutkast för förvaltningsberättelse och noter utifrån kända uppgifter. Ändrar aldrig siffror/RR/BR, hittar inte på jämförelsetal/noter/säkerheter, godkänner inget. Markeras ai_generated + kräver granskning (modell/prompt/tidpunkt visas). Manuell redigering kräver ny granskning. Ingår inte: PDF, e-inlämning, signering.'],
    ],
    errors: [
      ['"…ingår inte i din nuvarande plan"', 'Funktionen är licensstyrd – kontakta BokPilot för att lägga till den i planen.'],
      ['"Behörighet saknas: din roll får inte…"', 'Endast admin kan markera klar/ignorera och ändra status. Be en admin eller ändra roll under Inställningar → Team.'],
      ['"Engagemanget är låst"', 'Status är Låst (endast läsning). Låsning kan i nuläget inte ångras – kontakta BokPilot om det skett av misstag.'],
      ['"Ingen analys körd"', 'Klicka "Kör analys" för att bygga checklistan för valt räkenskapsår.'],
    ],
    example: 'Inför bokslut 2026: kör analys, åtgärda en kritisk "Bokföringen balanserar inte" och några höga risker, markera resten granskade, sätt "Klar för konsult" och slutligen "Godkänd". Allt loggas i spårbarheten.' }),

  // ─────────────────────────── Rapporter ───────────────────────────
  a({ id: 'help-report-result', slug: 'rapport-resultat', title: 'Resultatrapport', category: 'Rapporter',
    keywords: ['resultat', 'rapport', 'intäkter', 'kostnader', 'p&l'], related: ['rapport-balans', 'rapport-huvudbok', 'exportera-rapporter'],
    summary: 'Visa intäkter, kostnader och resultat för en period.',
    purpose: 'Ger lönsamhetsbilden (resultaträkning).',
    when: 'Vid uppföljning och bokslut.',
    steps: ['Gå till Rapporter → Resultatrapport.', 'Välj period.', 'Granska intäkter, kostnader och resultat.'],
    fields: [['Period', 'Månad/kvartal/år.']],
    errors: [['Oväntat resultat', 'Borra ner via Kontoanalys.']],
    example: 'Resultatrapport för juni visar månadens resultat.' }),

  a({ id: 'help-report-balance', slug: 'rapport-balans', title: 'Balansrapport', category: 'Rapporter',
    keywords: ['balans', 'rapport', 'tillgångar', 'skulder', 'eget kapital'], related: ['rapport-resultat', 'rapport-huvudbok'],
    summary: 'Visa tillgångar, skulder och eget kapital.',
    purpose: 'Ger ställningen vid en tidpunkt (balansräkning).',
    when: 'Vid period-/bokslut.',
    steps: ['Gå till Rapporter → Balansrapport.', 'Välj datum.', 'Kontrollera att balansen går ihop.'],
    fields: [],
    errors: [['Balansen stämmer inte', 'Kontrollera ofullständiga verifikationer.']],
    example: 'Balansrapport per 30 juni.' }),

  a({ id: 'help-report-ledger', slug: 'rapport-huvudbok', title: 'Huvudbok', category: 'Rapporter',
    keywords: ['huvudbok', 'rapport', 'konto', 'transaktioner'], related: ['rapport-verifikationslista', 'kontoanalys-oversikt'],
    summary: 'Alla transaktioner per konto.',
    purpose: 'Detaljerad genomgång konto för konto.',
    when: 'Vid analys och revision.',
    steps: ['Gå till Rapporter → Huvudbok.', 'Välj period/konto.', 'Granska transaktionerna.'],
    fields: [],
    errors: [],
    example: 'Huvudbok för 1930 visar alla bankhändelser.' }),

  a({ id: 'help-report-verlist', slug: 'rapport-verifikationslista', title: 'Verifikationslista', category: 'Rapporter',
    keywords: ['verifikationslista', 'verifikationer', 'rapport'], related: ['rapport-huvudbok', 'skapa-verifikation'],
    summary: 'Lista alla verifikationer i nummerordning.',
    purpose: 'Spårbarhet och kontroll av verifikationsserier.',
    when: 'Vid revision och kontroll.',
    steps: ['Gå till Rapporter → Verifikationslista.', 'Välj period/serie.', 'Öppna en verifikation för detaljer.'],
    fields: [],
    errors: [['Hopp i nummerserien', 'Kontrollera makulerade/raderade verifikationer.']],
    example: 'Verifikationslista A-serien för räkenskapsåret.' }),

  a({ id: 'help-report-export', slug: 'exportera-rapporter', title: 'Exportera rapporter', category: 'Rapporter',
    keywords: ['export', 'sie', 'excel', 'pdf', 'rapport'], related: ['rapport-resultat', 'rapport-balans'],
    summary: 'Exportera rapporter och bokföring (SIE/Excel/PDF).',
    purpose: 'Dela med revisor eller överför till annat system.',
    when: 'Vid bokslut eller systembyte.',
    steps: ['Öppna rapporten eller Inställningar → Import/Export.', 'Välj format (SIE, Excel, PDF).', 'Exportera/ladda ner.'],
    fields: [['SIE', 'Standardformat för bokföringsexport.']],
    errors: [['Fel period i exporten', 'Kontrollera vald period innan export.']],
    example: 'Exportera SIE-fil till revisorn.' }),

  // ─────────────────────────── AI-granskning ───────────────────────────
  a({ id: 'help-ai-review', slug: 'ai-granskning-oversikt', title: 'AI-granskning', category: 'AI-granskning',
    keywords: ['granskning', 'ai', 'kontroll', 'moms', 'fel'], related: ['kontrollera-moms', 'vanliga-bokforingsfel', 'manuell-granskning-kravs'],
    summary: 'Automatisk kontroll som hittar bokförings- och momsfel.',
    purpose: 'Flaggar misstänkta fel (fel konto, fel moms, obalans) före moms/bokslut – visar var felet är.',
    when: 'Löpande och inför momsdeklaration/bokslut.',
    steps: ['Öppna AI-granskning.', 'Kör granskningen för perioden.', 'Gå igenom flaggade poster och åtgärda.'],
    fields: [['Allvarlighetsgrad', 'Prioritera kritiska flaggor först.']],
    errors: [['Falsk flagga', 'Bedöm posten – allt flaggat är inte fel, men bör kontrolleras.']],
    example: 'Granskningen hittar en leverantörsfaktura där momsen inte matchar kostnaden.' }),

  // ─────────────────────────── Kunder / Leverantörer / Produkter ───────────────────────────
  a({ id: 'help-customers', slug: 'kunder-register', title: 'Kunder', category: 'Kunder',
    keywords: ['kunder', 'register', 'kundregister'], related: ['lagg-till-forsta-kunden', 'skapa-kundfaktura'],
    summary: 'Hantera kundregistret.',
    purpose: 'Centralt register som återanvänds på kundfakturor.',
    when: 'När du lägger upp eller uppdaterar kunder.',
    steps: ['Gå till Register → Kunder.', 'Lägg till, sök eller redigera kunder.'],
    fields: [['Org.nr', 'För företagskunder/e-faktura.']],
    errors: [['Dubbletter', 'Sök innan du lägger till.']],
    example: 'Uppdatera en kunds adress inför fakturering.' }),

  a({ id: 'help-suppliers', slug: 'leverantorer-register', title: 'Leverantörer', category: 'Leverantörer',
    keywords: ['leverantörer', 'register'], related: ['lagg-till-forsta-leverantoren', 'skapa-leverantorsfaktura'],
    summary: 'Hantera leverantörsregistret.',
    purpose: 'Register med betaluppgifter och inlärda konteringsregler.',
    when: 'När du lägger upp eller uppdaterar leverantörer.',
    steps: ['Gå till Register → Leverantörer.', 'Lägg till, sök eller redigera.'],
    fields: [['Bankgiro/Plusgiro', 'Betaluppgifter.']],
    errors: [],
    example: 'Lägg in bankgiro så betalning kan ske.' }),

  a({ id: 'help-products', slug: 'produkter-register', title: 'Produkter', category: 'Produkter',
    keywords: ['produkter', 'artiklar', 'register', 'pris'], related: ['skapa-kundfaktura', 'fakturamallar'],
    summary: 'Hantera produkt-/artikelregistret.',
    purpose: 'Återanvändbara artiklar med pris och momssats på kundfakturor.',
    when: 'När du säljer återkommande varor/tjänster.',
    steps: ['Gå till Register → Produkter.', 'Lägg till artikel med pris och momssats.', 'Ev. artikelkontering för automatisk bokföring.'],
    fields: [['Momssats', '25/12/6/0 %.'], ['Artikelkontering', 'Konto som används vid fakturering.']],
    errors: [],
    example: 'Lägg upp "Konsulttimme" med pris och 25 % moms.' }),

  // ─────────────────────────── OCR och AI-tolkning ───────────────────────────
  a({ id: 'help-ocr-how', slug: 'ai-tolkning-fungerar', title: 'Hur AI-tolkning fungerar', category: 'OCR och AI-tolkning',
    keywords: ['ocr', 'ai', 'tolkning', 'gemini', 'confidence'], related: ['vad-confidence-betyder', 'manuell-granskning-kravs', 'kvotfel-rate-limits'],
    summary: 'Så läser BokPilot underlag och föreslår kontering.',
    purpose: 'AI:n (Google Gemini) läser bild/PDF, extraherar fält och föreslår en balanserad kontering.',
    when: 'Bakgrundskunskap när du använder Tolka underlaget.',
    steps: ['Underlaget skickas till AI som returnerar strukturerad data.', 'Fälten fylls i och en kontering föreslås.', 'Du granskar och bokför – appen bokför aldrig automatiskt.'],
    fields: [['_meta', 'Resultatet sparar vilken modell/promptversion som användes (spårbarhet).']],
    errors: [['Tolkning blev fel', 'Granska mot bilden och rätta – appen lär sig av korrigeringar.']],
    example: 'Ett kvitto blir konteringsrader med netto + moms.' }),

  a({ id: 'help-confidence', slug: 'vad-confidence-betyder', title: 'Vad confidence betyder', category: 'OCR och AI-tolkning',
    keywords: ['confidence', 'konfidens', 'säkerhet', 'granskning'], related: ['ai-tolkning-fungerar', 'manuell-granskning-kravs'],
    summary: 'Konfidens = AI:ns säkerhet per fält (0–1).',
    purpose: 'Visar vilka fält du särskilt bör kontrollera.',
    when: 'När du granskar ett tolkat underlag.',
    steps: ['Titta på konfidensen per fält.', 'Lågt värde (under ~0,8) = dubbelkolla mot bilden.'],
    fields: [['1,0', 'Tydligt och otvetydigt.'], ['< 0,80', 'Härlett/handskrivet/suddigt – granska.']],
    errors: [['Litar blint på låg konfidens', 'Kontrollera fältet mot underlaget innan bokföring.']],
    example: 'Belopp 0,95 men fakturanummer 0,4 → kontrollera fakturanumret.' }),

  a({ id: 'help-manual-review', slug: 'manuell-granskning-kravs', title: 'När manuell granskning krävs', category: 'OCR och AI-tolkning',
    keywords: ['manuell', 'granskning', 'kontroll', 'osäkert'], related: ['vad-confidence-betyder', 'ai-granskning-oversikt'],
    summary: 'Fall där du alltid bör granska själv.',
    purpose: 'AI är ett stöd – vissa situationer kräver mänsklig bedömning.',
    when: 'Vid låg konfidens, ovanliga underlag eller skattefrågor.',
    steps: ['Granska vid låg konfidens.', 'Granska omvänd skattskyldighet, EU/import, periodisering och bokslutsbedömningar.', 'Bokför först när du är säker.'],
    fields: [],
    errors: [['Bokfört osäkert förslag', 'Ändra och bokför rätt; AI flaggar när granskning bör ske.']],
    example: 'EU-inköp med omvänd moms → granska manuellt.' }),

  a({ id: 'help-ai-learning', slug: 'hur-bokpilot-lar-sig', title: 'Hur BokPilot lär sig av korrigeringar', category: 'OCR och AI-tolkning',
    keywords: ['lärande', 'inlärd regel', 'korrigering', 'leverantör'], related: ['kontera-leverantorsfaktura', 'ai-tolkning-fungerar'],
    summary: 'Dina rättelser förbättrar framtida förslag.',
    purpose: 'BokPilot kommer ihåg återkommande mönster (t.ex. konto per leverantör).',
    when: 'Automatiskt när du rättar en kontering.',
    steps: ['Rätta konteringen när förslaget är fel.', 'Nästa gång för samma leverantör/butik föreslås det du brukar använda.'],
    fields: [['Inlärd regel', 'Kopplas till leverantör/butik med konfidens.']],
    errors: [['Fel inlärt mönster', 'Rätta igen – mönstret uppdateras, och regler kan tas bort.']],
    example: 'Efter att du kontterat en leverantör några gånger fylls kontot i automatiskt.' }),

  a({ id: 'help-quota', slug: 'kvotfel-rate-limits', title: 'Kvotfel och rate limits', category: 'OCR och AI-tolkning',
    keywords: ['kvot', 'rate limit', '429', 'gemini', 'cooldown'], related: ['vanliga-fel-ai-tolkning', 'felsokning-ocr'],
    summary: 'Varför AI-tolkningen ibland säger att kvoten är slut.',
    purpose: 'Google Gemini har per-minut- och dygnsgränser. BokPilot skyddar mot "retry-storm".',
    when: 'När du ser "AI-kvoten är tillfälligt slut".',
    steps: ['Vänta tills nedräkningen (cooldown) är klar.', 'Tryck Tolka EN gång – inte upprepat.', 'Appen provar flera modeller automatiskt.'],
    fields: [['Cooldown', 'Knappen är inaktiv en kort stund efter ett kvotfel.']],
    errors: [['Återkommande kvotfel', 'Kontrollera att API-nyckeln ligger på ett betalt projekt med aktiv fakturering.']],
    example: 'Felkod `429 RESOURCE_EXHAUSTED` → vänta 60 s och försök igen.' }),

  a({ id: 'help-ocr-troubleshoot', slug: 'felsokning-ocr', title: 'Felsökning av OCR', category: 'OCR och AI-tolkning',
    keywords: ['felsökning', 'ocr', 'fel', 'timeout', 'bild'], related: ['vanliga-fel-ai-tolkning', 'kvotfel-rate-limits'],
    summary: 'Steg för att lösa tolkningsproblem.',
    purpose: 'Hjälper dig komma vidare när tolkningen krånglar.',
    when: 'När Tolka underlaget inte ger resultat.',
    steps: ['Kontrollera bildkvalitet (skärpa, hela underlaget med).', 'Vänta vid kvot/överbelastning och försök igen.', 'Fyll i manuellt om underlaget är svårläst – det är inte fel på dig.'],
    fields: [],
    errors: [['"AI-tjänsten kunde inte tolka just nu"', 'Tillfälligt fel/överbelastning – försök igen om en stund.'], ['Timeout', 'Stora/komplexa PDF:er kan ta tid – försök igen.']],
    example: 'En skarp, rak bild ger klart bättre tolkning än en sned mobilbild.' }),

  // ─────────────────────────── Inställningar ───────────────────────────
  a({ id: 'help-company-settings', slug: 'foretagsinstallningar', title: 'Företagsinställningar', category: 'Inställningar',
    keywords: ['inställningar', 'företag', 'uppgifter'], related: ['grundinstallningar', 'kontoplan', 'anvandare-behorigheter'],
    summary: 'Företagets grunduppgifter.',
    purpose: 'Namn, org.nr och andra uppgifter som används i hela appen.',
    when: 'Vid uppstart och vid ändringar.',
    steps: ['Gå till Inställningar.', 'Uppdatera uppgifter.', 'Spara.'],
    fields: [['Org.nr', 'Företagets identitet.']],
    errors: [],
    example: 'Uppdatera adress inför fakturering.' }),

  a({ id: 'help-chart-of-accounts', slug: 'kontoplan', title: 'Kontoplan', category: 'Inställningar',
    keywords: ['kontoplan', 'konto', 'bas', 'momskod', 'sru'], related: ['grundinstallningar', 'skapa-verifikation'],
    summary: 'Hantera företagets BAS-kontoplan.',
    purpose: 'Konton som används vid all kontering.',
    when: 'När du behöver lägga till/ändra konton.',
    steps: ['Gå till Inställningar → Kontoplan.', 'Sök konto eller lägg till nytt.', 'Redigera kontonr, benämning, momskod och ev. SRU.'],
    fields: [['Momskod', 'Styr momsbehandlingen.'], ['SRU', 'Används vid deklaration/SRU-export (kan lämnas tomt i löpande bokföring).'], ['Låst konto', 'Standardkonton kan vara låsta och kan inte ändras.']],
    errors: [['"Kontot finns inte i kontoplanen"', 'Lägg upp kontot; vid stora kontoplaner hämtas alla konton (inte bara de första).'], ['Redigera visar tomt', 'Öppna kontot igen – fälten fylls från kontoplanen.']],
    example: 'Lägg till konto 6991 för övriga kostnader.' }),

  a({ id: 'help-users-roles', slug: 'anvandare-behorigheter', title: 'Användare och behörigheter', category: 'Inställningar',
    keywords: ['användare', 'team', 'behörighet', 'roll', 'bjuda in'], related: ['foretagsinstallningar', 'logga-in'],
    summary: 'Bjud in kollegor och styr åtkomst.',
    purpose: 'Flera användare kan dela på arbetet med rätt behörighet.',
    when: 'När fler ska arbeta i företaget.',
    steps: ['Gå till Inställningar → Team.', 'Bjud in användare via e-post.', 'Sätt roll/behörighet.'],
    fields: [['Roll', 'Styr vad användaren får göra.']],
    errors: [['Inbjudan kom inte fram', 'Kontrollera e-postadressen och be användaren kolla skräppost.']],
    example: 'Bjud in en kollega som användare.' }),

  a({ id: 'help-email-inbound', slug: 'epost-inkommande-underlag', title: 'E-post och inkommande underlag', category: 'Inställningar',
    keywords: ['e-post', 'inkommande', 'underlag', 'arkivnummer', 'inkorg'], related: ['epost-for-underlag', 'ladda-upp-underlag'],
    summary: 'Ställ in mejladressen som tar emot underlag.',
    purpose: 'Underlag som mejlas in hamnar automatiskt i Inkorgen.',
    when: 'Vid uppstart eller när du vill dela adressen.',
    steps: ['Hämta företagets inkorgsadress under Inställningar.', 'Dela den med leverantörer eller vidarebefordra själv.'],
    fields: [['Adress', 'Format `{arkivnummer}underlag@bokpilot.se`.']],
    errors: [['Fel adress', 'Använd exakt företagets arkivnummer.']],
    example: 'Lägg in `8063151underlag@bokpilot.se` hos en återkommande leverantör.' }),

  a({ id: 'help-integrations', slug: 'integrationer', title: 'Integrationer', category: 'Inställningar',
    keywords: ['integration', 'import', 'export', 'sie', 'bank'], related: ['exportera-rapporter', 'importera-bankhandelser'],
    summary: 'Koppla import/export och externa flöden.',
    purpose: 'Flytta data till/från BokPilot (t.ex. SIE).',
    when: 'Vid systembyte eller dataöverföring.',
    steps: ['Gå till Inställningar → Import/Export.', 'Välj typ (SIE m.m.) och kör.'],
    fields: [],
    errors: [['Importen fel', 'Kontrollera filformat och period.']],
    example: 'Importera SIE från tidigare system.' }),

  a({ id: 'help-ai-settings', slug: 'ai-installningar', title: 'AI-inställningar', category: 'Inställningar',
    keywords: ['ai', 'inställningar', 'tolkning', 'granskning'], related: ['ai-tolkning-fungerar', 'kvotfel-rate-limits'],
    summary: 'Inställningar som rör AI-funktionerna.',
    purpose: 'Styr hur AI-tolkning och AI-stöd används.',
    when: 'Vid behov av att justera AI-beteende.',
    steps: ['Gå till Inställningar.', 'Justera AI-relaterade val.'],
    fields: [],
    errors: [['AI svarar inte', 'Se Kvotfel och rate limits.']],
    example: 'Kontrollera AI-relaterade inställningar vid problem.' }),

  // ─────────────────────────── Billing och abonnemang ───────────────────────────
  a({ id: 'help-billing', slug: 'billing-abonnemang', title: 'Billing och abonnemang', category: 'Billing och abonnemang',
    keywords: ['abonnemang', 'betalning', 'plan', 'billing', 'faktura'], related: ['foretagsinstallningar'],
    summary: 'Hantera abonnemang och betalning för BokPilot.',
    purpose: 'Visar plan, status och betalningsuppgifter.',
    when: 'Vid uppgradering eller ändrad betalning.',
    steps: ['Gå till Inställningar → Abonnemang.', 'Se plan och status.', 'Uppdatera betalning vid behov.'],
    fields: [['Plan', 'Styr gränser och funktioner.']],
    errors: [['Tjänsten pausad', 'Kontakta BokPilot support – företaget kan vara pausat.']],
    example: 'Uppgradera planen när antalet underlag ökar.' }),

  // ─────────────────────────── Support ───────────────────────────
  a({ id: 'help-support', slug: 'kontakta-support', title: 'Kontakta support', category: 'Support',
    keywords: ['support', 'hjälp', 'kontakt', 'ärende'], related: ['ai-assistent'],
    summary: 'Få hjälp när handboken inte räcker.',
    purpose: 'Skapa ett supportärende med rätt sammanhang.',
    when: 'När du fastnat trots handbok och AI-hjälp.',
    steps: ['Öppna Support i sidomenyn (under Hjälp).', 'Beskriv problemet.', 'Bifoga gärna vilken vy och vilket underlag det gäller.'],
    fields: [['Sammanhang', 'Vy, roll och företag hjälper supporten.']],
    errors: [['Skicka inte känsliga underlag via WhatsApp', 'WhatsApp är endast enkel support, inte för dokument.']],
    example: 'Skapa ärende: "Kan inte bokföra – differens kvar".' }),

  // ─────────────────────────── Superadmin (behörig) ───────────────────────────
  a({ id: 'help-superadmin', slug: 'superadmin', title: 'Superadmin', category: 'Superadmin', role: 'admin',
    keywords: ['superadmin', 'admin', 'plattform', 'företag'], related: ['systemovervakning'],
    summary: 'Plattformsadministration för behöriga.',
    purpose: 'Hantera företag, åtkomst och plattformsinställningar.',
    when: 'Endast för plattformsadministratörer.',
    steps: ['Öppna Superadmin under Plattform.', 'Hantera företag och behörigheter.'],
    fields: [['service_state', 'active/paused/blocked styr om företaget kan ändra data.']],
    errors: [['Företag kan inte bokföra', 'Kontrollera om service_state är paused/blocked.']],
    example: 'Pausa ett företag som inte betalat.' }),

  // ─────────────────────────── Systemövervakning (behörig) ───────────────────────────
  a({ id: 'help-monitoring', slug: 'systemovervakning', title: 'Systemövervakning', category: 'Systemövervakning', role: 'ops',
    keywords: ['systemövervakning', 'drift', 'fel', 'health', 'loggar'], related: ['superadmin', 'kvotfel-rate-limits'],
    summary: 'Drift- och felövervakning för behöriga.',
    purpose: 'Se systemhälsa, fel och AI-/OCR-status.',
    when: 'Endast för drift/övervakning.',
    steps: ['Öppna Systemövervakning under Plattform.', 'Granska health, fel och loggar.'],
    fields: [['Worker health', 'Status för OCR/inbound m.m.'], ['Felkoder', 'T.ex. gemini_rate_limit, ocr_timeout.']],
    errors: [['Många OCR-fel', 'Kontrollera Gemini-kvot/nyckel och felkoder i loggen.']],
    example: 'Felkoden `gemini_rate_limit` indikerar kvotgräns.' }),
]

export const ARTICLE_BY_SLUG = Object.fromEntries(HELP_ARTICLES.map(x => [x.slug, x]))
export const ARTICLE_BY_ID = Object.fromEntries(HELP_ARTICLES.map(x => [x.id, x]))
